In [1]:
pip install google.api.python.client

Requirement already satisfied: google.api.python.client in c:\users\pranesh\anaconda3\lib\site-packages (2.90.0)
Requirement already satisfied: httplib2<1.dev0,>=0.15.0 in c:\users\pranesh\anaconda3\lib\site-packages (from google.api.python.client) (0.22.0)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in c:\users\pranesh\anaconda3\lib\site-packages (from google.api.python.client) (0.1.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\pranesh\anaconda3\lib\site-packages (from google.api.python.client) (4.1.1)
Requirement already satisfied: google-auth<3.0.0.dev0,>=1.19.0 in c:\users\pranesh\anaconda3\lib\site-packages (from google.api.python.client) (2.21.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in c:\users\pranesh\anaconda3\lib\site-packages (from google.api.python.client) (2.11.1)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in c:\users\pranesh\anaconda3\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google.api.python.client) (4.23.3)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in c:\users\pranesh\anaconda3\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google.api.python.client) (2.28.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in c:\users\pranesh\anaconda3\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google.api.python.client) (1.59.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\pranesh\anaconda3\lib\site-packages (from google-auth<3.0.0.dev0,>=1.19.0->google.api.python.client) (4.9)
Requirement already satisfied: urllib3<2.0 in c:\users\pranesh\anaconda3\lib\site-packages (from google-auth<3.0.0.dev0,>=1.19.0->google.api.python.client) (1.26.14)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\pranesh\anaconda3\lib\site-packages (from google-auth<3.0.0.dev0,>=1.19.0->google.api.python.client) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\pranesh\anaconda3\lib\site-packages (from google-auth<3.0.0.dev0,>=1.19.0->google.api.python.client) (5.3.1)
Requirement already satisfied: six>=1.9.0 in c:\users\pranesh\anaconda3\lib\site-packages (from google-auth<3.0.0.dev0,>=1.19.0->google.api.python.client) (1.16.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\users\pranesh\anaconda3\lib\site-packages (from httplib2<1.dev0,>=0.15.0->google.api.python.client) (3.0.9)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\pranesh\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0.dev0,>=1.19.0->google.api.python.client) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pranesh\anaconda3\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google.api.python.client) (2022.12.7)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\pranesh\anaconda3\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google.api.python.client) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pranesh\anaconda3\lib\site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google.api.python.client) (3.4)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from googleapiclient.discovery import build
import pandas as pd

In [45]:
pip install Ipython

Requirement already satisfied: Ipython in c:\users\pranesh\anaconda3\lib\site-packages (8.10.0)
Requirement already satisfied: colorama in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (0.4.6)
Requirement already satisfied: pygments>=2.4.0 in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (2.15.1)
Requirement already satisfied: decorator in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (5.1.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (3.0.36)
Requirement already satisfied: stack-data in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (0.2.0)
Requirement already satisfied: backcall in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (0.2.0)
Requirement already satisfied: pickleshare in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (0.7.5)
Requirement already satisfied: jedi>=0.16 in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (0.18.1)
Requirement already satisfied: traitlets>=5 in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (5.7.1)
Requirement already satisfied: matplotlib-inline in c:\users\pranesh\anaconda3\lib\site-packages (from Ipython) (0.1.6)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\pranesh\anaconda3\lib\site-packages (from jedi>=0.16->Ipython) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\pranesh\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.30->Ipython) (0.2.5)
Requirement already satisfied: asttokens in c:\users\pranesh\anaconda3\lib\site-packages (from stack-data->Ipython) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\pranesh\anaconda3\lib\site-packages (from stack-data->Ipython) (0.2.2)
Requirement already satisfied: executing in c:\users\pranesh\anaconda3\lib\site-packages (from stack-data->Ipython) (0.8.3)
Requirement already satisfied: six in c:\users\pranesh\anaconda3\lib\site-packages (from asttokens->stack-data->Ipython) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [89]:
from googleapiclient.errors import HttpError
import json
import re

In [90]:
api_key = "AIzaSyDQn72EMeyGBozU6vC4tFjncvRGvUQLGzo"

In [91]:
#api_key = 'AIzaSyDH_Y9CrF1YKw0k-FfyDbns40ne05huRhU'
api_service_name = "youtube"
api_version = "v3"
youtube =build(api_service_name, api_version, developerKey= api_key)

# Function for one channel info

In [192]:
channel_id='UCnz-ZXXER4jOvuED5trXfEA'# techTFQ
#channel_id='UUiv4AccPaqsv_Jdr2dmu92A' #mycycling spot

In [193]:
def get_channel_stats(youtube,channel_id):
    request = youtube.channels().list(
                part='snippet,contentDetails,statistics',
                id=channel_id)
    response = request.execute() 
    data = dict(Channel_name = response['items'][0]['snippet']['title'],
                    Subscribers = response['items'][0]['statistics']['subscriberCount'],
                    Views = response['items'][0]['statistics']['viewCount'],
                    Total_videos = response['items'][0]['statistics']['videoCount']
                   
               )
    return data

In [194]:
channel_details = get_channel_stats(youtube,channel_id)
channel_details

{'Channel_name': 'techTFQ',
 'Subscribers': '218000',
 'Views': '10913123',
 'Total_videos': '89'}

# Function to get multiple channel details

In [111]:
#channel_ids = ["UCxQuP9Qv49QnWeUY7Tp1HOw","RuuXzTIr0OoDqI4S0RU6n4FqKEM"]
channel_ids=['UCnz-ZXXER4jOvuED5trXfEA',"UC_x5XG1OV2P6uZZ5FSM9Ttw","UCsBX7Ui2qnM27GXVaZ1F3kQ","UCxQuP9Qv49QnWeUY7Tp1HOw","UCBnZ16ahKA2DZ_T5W0FPUXg",
              "UCk3JZr7eS3pg5AGEvBdEvFg","UChL9x-Q75LCuYHIFRDT_T1A","UCvrhwpnp2DHYQ1CbXby9ypQ","UCmxUSaxdeXP5eTfZUSIRSxg",
             "UCduIoIMfD8tT3KoU0-zBRgQ","UCgcUFVynuKwaIZLJkjhzOVg","UCBbgQlTV9z0qwjeofwtkhWg","UCiv4AccPaqsv_Jdr2dmu92A"]

In [112]:
def get_channel_stats(youtube, channel_ids):
    all_data = []
    request = youtube.channels().list(
                part='snippet,contentDetails,statistics',
                id=','.join(channel_ids))
    response = request.execute() 
    
    for i in range(len(response['items'])):
        data = dict(Channel_name = response['items'][i]['snippet']['title'],
                    Subscribers = response['items'][i]['statistics']['subscriberCount'],
                    Views = response['items'][i]['statistics']['viewCount'],
                    Total_videos = response['items'][i]['statistics']['videoCount'],
                    playlist_id = response['items'][i]['contentDetails']['relatedPlaylists']['uploads'])
        all_data.append(data)
    
    return all_data

In [113]:
channel_stats=get_channel_stats(youtube,channel_ids)
channel_stats

[{'Channel_name': 'GUVI',
  'Subscribers': '79100',
  'Views': '2680727',
  'Total_videos': '1041',
  'playlist_id': 'UUduIoIMfD8tT3KoU0-zBRgQ'},
 {'Channel_name': 'MaddyEats',
  'Subscribers': '4160000',
  'Views': '1205413124',
  'Total_videos': '410',
  'playlist_id': 'UUgcUFVynuKwaIZLJkjhzOVg'},
 {'Channel_name': 'News7Tamil Bakthi',
  'Subscribers': '150000',
  'Views': '40496397',
  'Total_videos': '5632',
  'playlist_id': 'UUBbgQlTV9z0qwjeofwtkhWg'},
 {'Channel_name': 'techTFQ',
  'Subscribers': '218000',
  'Views': '10913123',
  'Total_videos': '89',
  'playlist_id': 'UUnz-ZXXER4jOvuED5trXfEA'},
 {'Channel_name': 'D Sathish',
  'Subscribers': '0',
  'Views': '0',
  'Total_videos': '0',
  'playlist_id': 'UUxQuP9Qv49QnWeUY7Tp1HOw'},
 {'Channel_name': 'ChuChu TV Nursery Rhymes & Kids Songs',
  'Subscribers': '66100000',
  'Views': '45958410338',
  'Total_videos': '633',
  'playlist_id': 'UUBnZ16ahKA2DZ_T5W0FPUXg'},
 {'Channel_name': 'Village Cooking Channel',
  'Subscribers': '21800000',
  'Views': '5952842631',
  'Total_videos': '219',
  'playlist_id': 'UUk3JZr7eS3pg5AGEvBdEvFg'},
 {'Channel_name': "Irfan'sView Shorts",
  'Subscribers': '837000',
  'Views': '435666513',
  'Total_videos': '742',
  'playlist_id': 'UUhL9x-Q75LCuYHIFRDT_T1A'},
 {'Channel_name': 'Vijay Television',
  'Subscribers': '20500000',
  'Views': '29806914317',
  'Total_videos': '51580',
  'playlist_id': 'UUvrhwpnp2DHYQ1CbXby9ypQ'},
 {'Channel_name': 'MY CYCLING SPOT',
  'Subscribers': '1110',
  'Views': '65224',
  'Total_videos': '56',
  'playlist_id': 'UUiv4AccPaqsv_Jdr2dmu92A'},
 {'Channel_name': 'Google for Developers',
  'Subscribers': '2300000',
  'Views': '234125509',
  'Total_videos': '5787',
  'playlist_id': 'UU_x5XG1OV2P6uZZ5FSM9Ttw'},
 {'Channel_name': 'Vishal Pandey',
  'Subscribers': '1040000',
  'Views': '811535316',
  'Total_videos': '757',
  'playlist_id': 'UUmxUSaxdeXP5eTfZUSIRSxg'},
 {'Channel_name': 'Karthika Priyadharshini',
  'Subscribers': '36',
  'Views': '0',
  'Total_videos': '0',
  'playlist_id': 'UUsBX7Ui2qnM27GXVaZ1F3kQ'}]

# Function to get video_ids

In [117]:
playlist_id='UUnz-ZXXER4jOvuED5trXfEA'

In [118]:
def get_video_ids(youtube,channel_id):
    video_ids = []
    request = youtube.playlistItems().list(
        part="snippet,contentDetails",
        playlistId=playlist_id,
        maxResults = 50
    )
    response = request.execute()
    
    for item in response['items']:
        video_ids.append(item['contentDetails']['videoId'])
        next_page_token = response.get('nextPageToken')
    while next_page_token is not None:
        request = youtube.playlistItems().list(
                    part='contentDetails',
                    playlistId = playlist_id,
                    maxResults = 50,
                    pageToken = next_page_token)
        response = request.execute()

        for item in response['items']:
            video_ids.append(item['contentDetails']['videoId'])
            next_page_token = response.get('nextPageToken')
        
    return (video_ids)

In [119]:
video_ids= get_video_ids(youtube,playlist_id)

In [120]:
video_ids

['0QcEqFrhb_Y',
 'smztq8sRAhk',
 '7skZzocEU6c',
 'LZGaRcDxj8I',
 'rBPQ5fg_kiY',
 'hvwltYazuQo',
 'a-hFbr-4VQQ',
 'pMNcPLc9Z7c',
 'zZKb8FQRShs',
 'jS5_hjFgfzA',
 '6UAU79FNBjQ',
 'ZwFfiadQB3k',
 'Det4ZjBSe3M',
 'xUsY2jWQa1w',
 'ueOUSjdAZY8',
 '90iK6gGvG_g',
 'hsaPfEvForM',
 'jb8XlF2dkoY',
 'WhkNQ3g0U64',
 '_suB8xV9aPc',
 'dWHSt0BVlv0',
 'xJVWL7eMir0',
 'h48xzQR3wNQ',
 'S5gX-LLAZIM',
 'LNlzx-YX8rI',
 'WzkBZ0byoYE',
 'weCZ1WynbMI',
 '3dOxGYkpVbE',
 '9dLXZrw6nac',
 'i3xK7Nc414Q',
 'H7YMumanHBA',
 '4p-G7fGhqRk',
 'yLR1w4tZ36I',
 '-DiOp9vAEuM',
 'O1o9m9T1c3k',
 '7hZYh9qXxe4',
 'aE623ff7zkM',
 'eXJGjbDo5KY',
 'O52sweYbCyI',
 'cLSxasHg9WY',
 'l6XhSFAyvO0',
 'nJIEIzF7tDw',
 'RehbnzKHS28',
 '0OQJDd3QqQM',
 'V6KPbGLYL4A',
 'OIqm909GYYo',
 'xN2PRAd8IZQ',
 'AK7_m-aThfw',
 'CYszyA2Xzdg',
 'wT9ICgxRPYY',
 'XruOBp7yPXU',
 'SwSbnmqk3zY',
 '8p_OzqIJ_p4',
 '0Hhqf8L-b_0',
 'M2NzvnfS-hI',
 'QNfnuK-1YYY',
 'PuBadaR8qC4',
 'FNYdBLwZ6cE',
 'zAmJPdZu8Rg',
 'HJAwAKwFX-A',
 'kY5HtrkjSj0',
 'LCVSmkyB4v8',
 '6x7vHXfRAP0',
 '-DrSbc8B0WI',
 'gsa1oFn9n0M',
 'Ww71knvhQ-s',
 'Jsnw6HLASZA',
 'V_BozMwoYe4',
 '0wjPsKDrYt8',
 '1-z9ptlBar4',
 '35dXEQJkFE8',
 'jgNB4GN1UaQ',
 'fhxByMe0mq8',
 '5bwpXLHzZRo',
 'UzOnFDmoJ9w',
 'HNChkuE6HyA',
 '2gFqUWO-AWM',
 'NvdSKgQcyuc',
 'BBb_duZIusU',
 'PRGkYivK2xI',
 'M323OL6K5vs',
 'i7BjHjRafU8',
 'r2asdRpr3uw',
 'Hl4NZB1XR9c',
 '1aybOgni7lI',
 'j09EQ-xlh88',
 '7nzTDrio7vY',
 'J-uCLHTIWZ4',
 '_BMPh5M4BIY']

In [121]:
len(video_ids)

89

# good one

In [ ]:
data = dict(playlist_name = response['items'][0]['snippet']['title'],
             playlist_id = response['items'][0]['contentDetails']['description'])

In [185]:
get_playlist_id_from_channel(channel_id)

{'kind': 'youtube#playlistListResponse',
 'etag': 'cBNIoH-31to7DysMzzc-BkA2djo',
 'pageInfo': {'totalResults': 1, 'resultsPerPage': 50},
 'items': [{'kind': 'youtube#playlist',
   'etag': 'b48rQKLhwkijAorQFdMs2fGPdNE',
   'id': 'UUiv4AccPaqsv_Jdr2dmu92A',
   'snippet': {'publishedAt': '2021-05-30T13:24:35Z',
    'channelId': 'UCiv4AccPaqsv_Jdr2dmu92A',
    'title': 'Uploads from MY CYCLING SPOT',
    'description': '',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/9QDhesMz6eY/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/9QDhesMz6eY/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/9QDhesMz6eY/hqdefault.jpg',
      'width': 480,
      'height': 360},
     'standard': {'url': 'https://i.ytimg.com/vi/9QDhesMz6eY/sddefault.jpg',
      'width': 640,
      'height': 480},
     'maxres': {'url': 'https://i.ytimg.com/vi/9QDhesMz6eY/maxresdefault.jpg',
      'width': 1280,
      'height': 720}},
    'channelTitle': 'MY CYCLING SPOT',
    'defaultLanguage': 'en',
    'localized': {'title': 'Uploads from MY CYCLING SPOT', 'description': ''}},
   'contentDetails': {'itemCount': 56}}]}

In [184]:
def get_playlist_id_from_channel(channel_id):
    request = youtube.playlists().list(
        part='snippet,contentDetails',
        id=channel_id,
        maxResults=100
    )
    response = request.execute()
    
    return response

In [172]:
def get_playlist_id_from_channel(channel_id):
    playlist_ID = []
    request = youtube.playlists().list(
        part="snippet,contentDetails",
        id=channel_id,
        maxResults=50
    )
    response = request.execute()
    for item in response['items']:
        playlist_ID.append(item['contentDetails']['video_ids'])
        next_page_token = response.get('nextPageToken')
        while next_page_token is not None:
            request = youtube.playlists().list(
                      part="snippet,contentDetails",
                      id=channel_id,
                      maxResults=50,
                      pageToken = next_page_token)
            response = request.execute()

            for item in response['items']:
                playlist_ID.append(item['contentDetails']['video_ids'])
                next_page_token = response.get('nextPageToken')
        
    return playlist_ID

In [188]:
df=pd.DataFrame(video_df)
df

,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favouriteCount,commentCount,duration,definition,caption
0,0QcEqFrhb_Y,techTFQ,Learn SQL from me | Live SQL Training | SQL Bo...,"In this video, I highlight the 3 reasons why m...","[sql, learn sql for beginners, learn sql, sql ...",2023-05-25T14:35:13Z,19761,565,None,162,PT9M51S,hd,false
1,smztq8sRAhk,techTFQ,Learn Python here | Learn Python Programming here,"In this video, I will showcase a dedicated onl...","[learn python, python for beginners, python co...",2023-05-16T13:45:59Z,13060,241,None,20,PT6M30S,hd,false
2,7skZzocEU6c,techTFQ,Solving a Complex SQL Interview problem | Prac...,"In this video, let us solve a complex SQL inte...","[sql, learn sql, sql query, sql queries, sql p...",2023-03-21T13:00:12Z,31550,899,None,99,PT32M9S,hd,false
3,LZGaRcDxj8I,techTFQ,REAL SQL Interview Problem | Hierarchical data...,In this video let us solve a real SQL intervie...,"[sql, learn sql, sql queries, sql query, solvi...",2023-03-14T13:00:09Z,17114,676,None,56,PT22M9S,hd,false
4,rBPQ5fg_kiY,techTFQ,Complete guide to Database Normalization in SQL,This is a complete guide for anyone to underst...,"[database normalization, database normalizatio...",2023-03-07T13:00:07Z,45504,2142,None,221,PT40M51S,hd,false
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,1aybOgni7lI,techTFQ,How to install PostgreSQL on Mac OS | Install ...,This video is about how to install PostgreSQL ...,"[PostgreSQL, pgAdmin, Database, PostgreSQL Dat...",2020-11-16T02:28:09Z,69588,675,None,97,PT20M51S,hd,false
85,j09EQ-xlh88,techTFQ,Learn What is Database | Types of Database | DBMS,"In this video, we learn everything we need to ...","[Database, DBMS, Relational Database, Non-Rela...",2020-08-30T00:38:24Z,206831,3696,None,121,PT12M11S,hd,false
86,7nzTDrio7vY,techTFQ,Do you need a Smartwatch,"In this video, I talk about the advantageous o...","[Do you need a smartwatch, Samsung Galaxy Watc...",2020-07-12T15:32:36Z,11346,185,None,46,PT7M43S,hd,false
87,J-uCLHTIWZ4,techTFQ,MacBook Pro 13 2020 One Week Later Review,Macbook Pro 13 2020 review after one week. Qui...,None,2020-06-29T15:03:19Z,1375,71,None,20,PT9M24S,hd,false
88,_BMPh5M4BIY,techTFQ,MacBook Pro 13 2020 Unboxing,This video is about unboxing of New MacBook Pr...,"[#MacBookPro13, #Unboxing, #Apple, #Malaysia, ...",2020-06-22T14:49:50Z,2550,90,None,29,PT9M19S,hd,false

# starting again

In [186]:
def get_video_details(youtube, video_ids):
    """
    Get video statistics of all videos with given IDs
    Params:
    
    youtube: the build object from googleapiclient.discovery
    video_ids: list of video IDs
    
    Returns:
    Dataframe with statistics of videos, i.e.:
        'channelTitle', 'title', 'description', 'tags', 'publishedAt'
        'viewCount', 'likeCount', 'favoriteCount', 'commentCount'
        'duration', 'definition', 'caption'
    """
        
    all_video_info = []
    
    for i in range(0, len(video_ids), 50):
        request = youtube.videos().list(
            part="snippet,contentDetails,statistics",
            id=','.join(video_ids[i:i+50])
        )
        response = request.execute() 

        for video in response['items']:
            stats_to_keep = {'snippet': ['channelTitle', 'title', 'description', 'tags', 'publishedAt'],
                             'statistics': ['viewCount', 'likeCount', 'favouriteCount', 'commentCount'],
                             'contentDetails': ['duration', 'definition', 'caption']
                            }
            video_info = {}
            video_info['video_id'] = video['id']

            for k in stats_to_keep.keys():
                for v in stats_to_keep[k]:
                    try:
                        video_info[v] = video[k][v]
                    except:
                        video_info[v] = None

            all_video_info.append(video_info)
            
    return(all_video_info)

In [187]:
video_df=get_video_details(youtube, video_ids)
video_df

[{'video_id': '0QcEqFrhb_Y',
  'channelTitle': 'techTFQ',
  'title': 'Learn SQL from me | Live SQL Training | SQL Bootcamp',
  'description': 'In this video, I highlight the 3 reasons why many are struggling to learn SQL and how I can help with a couple of the reasons. I talk about the upcoming SQL Bootcamp on Lighthall and who should join this SQL Bootcamp.\nAnyone with zero knowledge of SQL or any programming language can join my SQL BootCamp and learn SQL.\n\nAll details about the SQL BootCamp are mentioned here: \nhttps://techtfq.com/sql-bootcamp\n\nJoin the SQL Bootcamp here:\nhttps://www.lighthall.co/class/242f82c8-8220-40e8-9674-ed6b3f596f09\n\n\nHere is a quick summary of the SQL Bootcamp below:\n\n -- Weekend class - 20 live sessions - reduced price ($30 / INR 2400)\n -- Beginner to Advance level SQL - Suitable for beginners\n -- Starts: 03-Jun-2023\n -- Timing: 07:30 pm IST (Indian time) / 10:00 am EST (Eastern time) / 04:00 pm CET (Central European time)\n -- Days: Only on Weekends (Saturday & Sunday)\n -- If you miss a live class, then watch the recordings.\n -- Recording will be available for up to 1 year\n\nTimeline of the video:\n00:00 Intro\n00:46 Reason no 1) for struggling to learn SQL\n02:01 Reason no 2) for struggling to learn SQL\n02:41 Reason no 3) for struggling to learn SQL\n03:17 How can I help in solving these problems?\n04:54 Details about my upcoming SQL Bootcamp\n05:13 Quick summary of my upcoming SQL Bootcamp\n\nThank you!',
  'tags': ['sql',
   'learn sql for beginners',
   'learn sql',
   'sql course',
   'sql training',
   'live sql training',
   'sql bootcamp',
   'sql tutorial',
   'techtfq',
   'sql techtfq',
   'techtfq sql',
   'sql practice',
   'sql queries'],
  'publishedAt': '2023-05-25T14:35:13Z',
  'viewCount': '19761',
  'likeCount': '565',
  'favouriteCount': None,
  'commentCount': '162',
  'duration': 'PT9M51S',
  'definition': 'hd',
  'caption': 'false'},
 {'video_id': 'smztq8sRAhk',
  'channelTitle': 'techTFQ',
  'title': 'Learn Python here | Learn Python Programming here',
  'description': 'In this video, I will showcase a dedicated online platform for learning Python.  This platform contains multiple different Python courses which are dedicated to complete beginners and also for advanced learners. You will find Python courses specific to Data science and data processing too. \n\nLink to the platform: https://fas.st/t/z1UT6m6w\nPROMO CODE: adtfq10\nThe above promo code gives a 10% discount but will be active only until 01/08/2023\n\nJoin my Live Training SQL Bootcamp starting 03-Jun-2023\nMore details: https://techtfq.com/sql-bootcamp\nJoin Bootcamp: https://www.lighthall.co/class/242f82c8-8220-40e8-9674-ed6b3f596f09\n\nThanks,\nThoufiq',
  'tags': ['learn python',
   'python for beginners',
   'python course',
   'python online course',
   'techtfq python',
   'techtfq',
   'techtfq sql',
   'learnpython.com',
   'python tutorial',
   'python tutorial for beginners',
   'best python course',
   'best platform to learn python'],
  'publishedAt': '2023-05-16T13:45:59Z',
  'viewCount': '13060',
  'likeCount': '241',
  'favouriteCount': None,
  'commentCount': '20',
  'duration': 'PT6M30S',
  'definition': 'hd',
  'caption': 'false'},
 {'video_id': '7skZzocEU6c',
  'channelTitle': 'techTFQ',
  'title': 'Solving a Complex SQL Interview problem | Practice SQL Queries',
  'description': 'In this video, let us solve a complex SQL interview problem. This is a REAL SQL Interview question that might seem impossible to solve just by using SQL at first. But during the video, I will simplify the problem by breaking it into multiple parts. \nWe shall first determine an approach that can solve such problems easily and then write the SQL query to solve this problem.\n\nYou can download the dataset, scripts, and solution from my website below:\nhttps://techtfq.com/blog/lets-simplify-and-solve-a-complex-sql-interview-problem\n\n\n🔴 My Recommended courses 👇\n✅ Learn complete SQL: https://learnsql.com/?ref=thoufiqmohammed\n\n✅ Practice SQL Queries: https://www.stratascratch.com/?via=techTFQ\n\n✅ Learn Python: https://codebasics.io/courses/python-for-beginner-and-intermediate-learners?refId=70170e4c-7511-4c83-b769-c5cc8339c731\n\n✅ Learn Power BI: https://codebasics.io/courses/power-bi-data-analysis-with-end-to-end-project?refId=4b1e1886-3252-4bf1-86f4-7d603dab692f\n\n\n🔴 WATCH MORE VIDEOS HERE 👇\n\n✅ SQL Tutorial - Basic concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HQQ_COgGb7kf_1H8UWUBxO\n\n✅ SQL Tutorial - Intermediate concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FD9XspliRM_HZM_jK7tkii\n\n✅ SQL Tutorial - Advance concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GbmgiW4TWVnxhjMFOIf0Q7\n\n✅ Practice Solving Basic SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9F66P3GFo5O6nJ4DfZNhVsp\n\n✅ Practice Solving Intermediate SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EIYmNXJ8ZtQ1bmLIpt0SpV\n\n✅ Practice Solving Complex SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9Fahr7taauUx5RnTfuGyL--\n\n✅ Data Analytics Career guidance:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FDsr995DjwCy9XNaIukb8P\n\n✅ SQL Course, SQL Training Platform Recommendations:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GqF1Q_zn8KnYvFgtEOh-2n\n\n✅ Python Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FePZXIo4jpsupqp3X0w2SW\n\n✅ Git and GitHub Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EI1MPlqqDpe3bgr8RJZE0b\n\n✅ Data Analytics Projects:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HwT_uStsDdJbuBOt_XD0ch\n\nTHANK YOU,\nThoufiq',
  'tags': ['sql',
   'learn sql',
   'sql query',
   'sql queries',
   'sql problem',
   'sql interview',
   'sql interview query',
   'sql interview problem',
   'solving sql query',
   'practice sql query',
   'complex sql query',
   'sql techtfq',
   'techtfq sql',
   'techtfq',
   'sql interview questions'],
  'publishedAt': '2023-03-21T13:00:12Z',
  'viewCount': '31550',
  'likeCount': '899',
  'favouriteCount': None,
  'commentCount': '99',
  'duration': 'PT32M9S',
  'definition': 'hd',
  'caption': 'false'},
 {'video_id': 'LZGaRcDxj8I',
  'channelTitle': 'techTFQ',
  'title': 'REAL SQL Interview Problem | Hierarchical data in SQL',
  'description': 'In this video let us solve a real SQL interview problem. This problem is to find the hierarchy of employees. \n\nWe shall first understand the problem statement and the given data before solving the problem.\nDuring the video, we shall also see how to debug a recursive SQL query. We shall try to come up with the different queries SQL generates during each iteration of the recursive SQL query. This will hopefully give you a complete understanding of how recursive SQL query works.\n\n🔴 My Recommended courses 👇\n✅ Learn complete SQL: https://learnsql.com/?ref=thoufiqmohammed\n\n✅ Practice SQL Queries: https://www.stratascratch.com/?via=techTFQ\n\n✅ Learn Python: https://codebasics.io/courses/python-for-beginner-and-intermediate-learners?refId=70170e4c-7511-4c83-b769-c5cc8339c731\n\n✅ Learn Power BI: https://codebasics.io/courses/power-bi-data-analysis-with-end-to-end-project?refId=4b1e1886-3252-4bf1-86f4-7d603dab692f\n\n\n🔴 WATCH MORE VIDEOS HERE 👇\n\n✅ SQL Tutorial - Basic concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HQQ_COgGb7kf_1H8UWUBxO\n\n✅ SQL Tutorial - Intermediate concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FD9XspliRM_HZM_jK7tkii\n\n✅ SQL Tutorial - Advance concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GbmgiW4TWVnxhjMFOIf0Q7\n\n✅ Practice Solving Basic SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9F66P3GFo5O6nJ4DfZNhVsp\n\n✅ Practice Solving Intermediate SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EIYmNXJ8ZtQ1bmLIpt0SpV\n\n✅ Practice Solving Complex SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9Fahr7taauUx5RnTfuGyL--\n\n✅ Data Analytics Career guidance:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FDsr995DjwCy9XNaIukb8P\n\n✅ SQL Course, SQL Training Platform Recommendations:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GqF1Q_zn8KnYvFgtEOh-2n\n\n✅ Python Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FePZXIo4jpsupqp3X0w2SW\n\n✅ Git and GitHub Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EI1MPlqqDpe3bgr8RJZE0b\n\n✅ Data Analytics Projects:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HwT_uStsDdJbuBOt_XD0ch\n\nTHANK YOU,\nThoufiq',
  'tags': ['sql',
   'learn sql',
   'sql queries',
   'sql query',
   'solving sql query',
   'solving sql problem',
   'sql interview query',
   'sql interview problem',
   'real sql interview',
   'real sql interview problem',
   'recursive sql',
   'hierarchical data in sql',
   'sql hierarchy',
   'sql recursion',
   'sql tutorial',
   'sql techtfq',
   'techtfq sql',
   'techtfq',
   'sql interview questions and answers',
   'sql interview questions',
   'interview question',
   'sql interview'],
  'publishedAt': '2023-03-14T13:00:09Z',
  'viewCount': '17114',
  'likeCount': '676',
  'favouriteCount': None,
  'commentCount': '56',
  'duration': 'PT22M9S',
  'definition': 'hd',
  'caption': 'false'},
 {'video_id': 'rBPQ5fg_kiY',
  'channelTitle': 'techTFQ',
  'title': 'Complete guide to Database Normalization in SQL',
  'description': 'This is a complete guide for anyone to understand Database Normalization in SQL. I will not just explain the Normalization concepts but also show you step by step process of normalizing a de-normalized dataset taken from Kaggle by following the different levels of normalization (Normal forms).\n\nThe video is divided into 3 sections: \nIn the first section, I will explain the basic concepts of normalization and the different levels of normalization (different normal forms), and some key points you need to know to better understand normalization.\nIn the second section, I will explain all the above concepts in detail with proper examples. We shall use a de-normalized dataset taken from Kaggle for illustration purposes. We shall follow different normal forms to normalize the Kaggle dataset which should give a complete understanding of how to normalize any dataset.\nFinally, in the third and last section, I shall explain the different anomalies that exist in a de-normalized dataset such as insertion, updation, and deletion anomalies. We shall also see how a normalized database can overcome these anomalies.\n\nTimestamp:\n00:00 Intro\n00:46 1. What is Normalization\n03:12 Different levels of Normalization\n05:14 2. Step-by-Step Normalizing a dataset\n07:35 First Normal Form (1NF)\n12:44 Second Normal Form (2NF)\n25:59 Third Normal Form (3NF)\n32:42 3. Different Anomalies (Insertion, Updation, Deletion Anomalies)\n37:10 Deletion Anomalies\n39:08 Updation Anomalies\n\n\n🔴 My Recommended courses 👇\n✅ Learn complete SQL: https://learnsql.com/?ref=thoufiqmohammed\n\n✅ Practice SQL Queries: https://www.stratascratch.com/?via=techTFQ\n\n✅ Learn Python: https://codebasics.io/courses/python-for-beginner-and-intermediate-learners?refId=70170e4c-7511-4c83-b769-c5cc8339c731\n\n✅ Learn Power BI: https://codebasics.io/courses/power-bi-data-analysis-with-end-to-end-project?refId=4b1e1886-3252-4bf1-86f4-7d603dab692f\n\n\n🔴 WATCH MORE VIDEOS HERE 👇\n\n✅ SQL Tutorial - Basic concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HQQ_COgGb7kf_1H8UWUBxO\n\n✅ SQL Tutorial - Intermediate concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FD9XspliRM_HZM_jK7tkii\n\n✅ SQL Tutorial - Advance concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GbmgiW4TWVnxhjMFOIf0Q7\n\n✅ Practice Solving Basic SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9F66P3GFo5O6nJ4DfZNhVsp\n\n✅ Practice Solving Intermediate SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EIYmNXJ8ZtQ1bmLIpt0SpV\n\n✅ Practice Solving Complex SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9Fahr7taauUx5RnTfuGyL--\n\n✅ Data Analytics Career guidance:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FDsr995DjwCy9XNaIukb8P\n\n✅ SQL Course, SQL Training Platform Recommendations:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GqF1Q_zn8KnYvFgtEOh-2n\n\n✅ Python Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FePZXIo4jpsupqp3X0w2SW\n\n✅ Git and GitHub Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EI1MPlqqDpe3bgr8RJZE0b\n\n✅ Data Analytics Projects:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HwT_uStsDdJbuBOt_XD0ch\n\nTHANK YOU,\nThoufiq',
  'tags': ['database normalization',
   'database normalization 1nf 2nf 3nf',
   'sql normalization',
   'database normalization in sql',
   'normalize database',
   'normal forms',
   '1nf',
   '2nf',
   '3nf',
   'sql',
   'learn sql',
   'sql turorial',
   'normalization in sql',
   'normalization tutorial',
   'normalization in database',
   'sql techtfq',
   'techtfq',
   'techtfq sql',
   'insertion anomalies',
   'deletion anomalies',
   'updation anomalies',
   'anomalies in dbms',
   'dbms normalization',
   'data redundancy',
   'candidate key',
   'partial dependancy',
   'transitive dependancy'],
  'publishedAt': '2023-03-07T13:00:07Z',
  'viewCount': '45504',
  'likeCount': '2142',
  'favouriteCount': None,
  'commentCount': '221',
  'duration': 'PT40M51S',
  'definition': 'hd',
  'caption': 'false'},
 {'video_id': 'hvwltYazuQo',
  'channelTitle': 'techTFQ',
  'title': 'SQL Live class on Lighthall | Learn SQL from Basic to Advance in SQL Bootcamp',
  'description': "In this video, I talk about the Live SQL Classes that I'll be taking on Lighthall from 01-Feb-2023. This SQL Bootcamp will cover Basic, Intermediate and Advance SQL.\n\nTimestamp:\n00:00 Intro\n00:40 Bootcamp details and Format\n02:16 Advantages of live class training over recorded courses\n04:22 Difference between learning SQL from my YouTube videos and SQL Bootcamp\n05:20 Who is this SQL bootcamp for?\n\n - 20 Live & Interactive SQL classes of 1.5 hrs each.\n - 3 classes per week\n - Starts on 01-Feb-2023\n - Recording will be available for 1 year\n - Certification provided\n - Cost = USD $50\n - Timing: 09:30 pm IST / 11:00 am EST\n\nJOIN Bootcamp here: https://www.lighthall.co/class/b608abfc-e3f4-43b3-a008-14bf8403b821\n\nOR go to my website for more details:\nhttps://techtfq.com/sql-bootcamp\n\nThanks,\nThoufiq",
  'tags': ['sql',
   'sql queries',
   'learn sql',
   'sql live class',
   'sql live classes',
   'sql bootcamp',
   'sql course',
   'sql training',
   'sql basic',
   'sql advance',
   'sql tutorial',
   'sql for beginners',
   'sql techtfq',
   'techtfq sql',
   'techtfq',
   'how to learn sql'],
  'publishedAt': '2023-01-26T07:00:07Z',
  'viewCount': '11763',
  'likeCount': '247',
  'favouriteCount': None,
  'commentCount': '150',
  'duration': 'PT6M46S',
  'definition': 'hd',
  'caption': 'false'},
 {'video_id': 'a-hFbr-4VQQ',
  'channelTitle': 'techTFQ',
  'title': 'How to learn SQL for free | Roadmap to learning SQL',
  'description': 'In this video, you will find complete roadmap on how to learn SQL for Beginners, Intermediate level, Advanced level and for database developers.\nYou will know how to choose a database and what SQL concepts you need to learn to have basic, intermediate, advanced and developer level knowledge of SQL.\n\nCheckout Bootcamp courses on Springboard: https://www.springboard.com/\n\nUse below promo code to get discounts on any Springboard course:\nPromo code: TechTFQNEWYEAR offers $1,250 (valid until 05-Jan-2023)\nPromo code: TechTFQ offers $1,000\n\nTimestamp:\n00:00 Intro of SQL Learning Roadmap\n01:44 Pre-Requisites required before learning SQL (which database, IDE etc)\n06:10 Springboard bootcamp course\n08:30 Basic SQL\n15:42 Intermediate level of SQL\n21:35 Advanced SQL\n24:08 SQL required for DB developers or SQL developers\n\nLearning Resources & Practice Platforms mentioned in the video can be found in detail in my blog. Link below:\nhttps://techtfq.com/blog/how-to-learn-sql-for-free-roadmap-to-learning-sql\n\n\n🔴 My Recommended courses 👇\n✅ Learn complete SQL: https://learnsql.com/?ref=thoufiqmohammed\n\n✅ Practice SQL Queries: https://www.stratascratch.com/?via=techTFQ\n\n✅ Learn Python: https://codebasics.io/courses/python-for-beginner-and-intermediate-learners?refId=70170e4c-7511-4c83-b769-c5cc8339c731\n\n✅ Learn Power BI: https://codebasics.io/courses/power-bi-data-analysis-with-end-to-end-project?refId=4b1e1886-3252-4bf1-86f4-7d603dab692f\n\n\n🔴 WATCH MORE VIDEOS HERE 👇\n\n✅ SQL Tutorial - Basic concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HQQ_COgGb7kf_1H8UWUBxO\n\n✅ SQL Tutorial - Intermediate concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FD9XspliRM_HZM_jK7tkii\n\n✅ SQL Tutorial - Advance concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GbmgiW4TWVnxhjMFOIf0Q7\n\n✅ Practice Solving Basic SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9F66P3GFo5O6nJ4DfZNhVsp\n\n✅ Practice Solving Intermediate SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EIYmNXJ8ZtQ1bmLIpt0SpV\n\n✅ Practice Solving Complex SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9Fahr7taauUx5RnTfuGyL--\n\n✅ Data Analytics Career guidance:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FDsr995DjwCy9XNaIukb8P\n\n✅ SQL Course, SQL Training Platform Recommendations:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GqF1Q_zn8KnYvFgtEOh-2n\n\n✅ Python Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FePZXIo4jpsupqp3X0w2SW\n\n✅ Git and GitHub Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EI1MPlqqDpe3bgr8RJZE0b\n\n✅ Data Analytics Projects:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HwT_uStsDdJbuBOt_XD0ch\n\nFTC disclaimer: This video was sponsored by Springboard.\n\nTHANK YOU,\nThoufiq',
  'tags': ['learn sql',
   'how to learn sql',
   'how to learn sql for free',
   'sql tutorial',
   'sql learning resources',
   'sql practice platforms',
   'sql roadmap',
   'roadmap to learning sql',
   'roadmap sql',
   'sql for beginners',
   'sql for intermediate',
   'advance sql',
   'sql for db developers',
   'prerequisites for learning sql',
   'sql learning prerequisites',
   'which database for learning sql'],
  'publishedAt': '2022-12-28T13:00:10Z',
  'viewCount': '354674',
  'likeCount': '11305',
  'favouriteCount': None,
  'commentCount': '364',
  'duration': 'PT27M20S',
  'definition': 'hd',
  'caption': 'false'},
 {'video_id': 'pMNcPLc9Z7c',
  'channelTitle': 'techTFQ',
  'title': 'Solving an SQL Interview Problem',
  'description': "In this video, let's solve an SQL interview query taken from LeetCode.\nThe problem might seem complex at first but there is a very simple solution to solve such problems so lets explore it in this video.\n\nLink to complete video: https://youtu.be/zZKb8FQRShs",
  'tags': ['sql',
   'learn sql',
   'sql tutorial',
   'solving sql queries',
   'sql interview query'],
  'publishedAt': '2022-12-18T13:39:48Z',
  'viewCount': '31692',
  'likeCount': '1310',
  'favouriteCount': None,
  'commentCount': '16',
  'duration': 'PT27S',
  'definition': 'hd',
  'caption': 'false'},
 {'video_id': 'zZKb8FQRShs',
  'channelTitle': 'techTFQ',
  'title': 'Solving SQL Interview Query | Find Tree Node type using SQL',

In [189]:
def get_comments_in_videos(youtube, video_ids):
    """
    Get top level comments as text from all videos with given IDs (only the first 10 comments due to quote limit of Youtube API)
    Params:
    
    youtube: the build object from googleapiclient.discovery
    video_ids: list of video IDs
    
    Returns:
    Dataframe with video IDs and associated top level comment in text.
    
    """
    all_comments = []
    
    for video_id in video_ids:
        try:   
            request = youtube.commentThreads().list(
                part="snippet,replies",
                videoId=video_id
            )
            response = request.execute()
        
            comments_in_video = [comment['snippet']['topLevelComment']['snippet']['textOriginal'] for comment in response['items'][0:10]]
            comments_in_video_info = {'video_id': video_id, 'comments': comments_in_video}

            all_comments.append(comments_in_video_info)
            
        except: 
            # When error occurs - most likely because comments are disabled on a video
            print('Could not get comments for video ' + video_id)
        
    return(all_comments)

In [190]:
comment_df=get_comments_in_videos(youtube, video_ids)
comment_df

[{'video_id': '0QcEqFrhb_Y',
  'comments': ['Great work... The way ur teaching is great.  ur videos helps me to get job🎉\nThanks. \nAwesome.. Go ahead. \nCan u do video -Why sql /plsql?\nFuture scope?',
   'Brother, I have a query like this: I have used "show Databases" in MYSQL and "select name from sys.databases" in SQL SERVER to retrieve the names of all databases. I successfully obtained the database names. Now, my question is, can I store this result set of database names in another existing table?',
   "I appreciate your videos and example queries. My main issue learning sql is that i don't understand how it applies to the on the job work.  Are data analysts being asked to write order, salary, and department queries? Meaning, what queries are employees writing on the job, rather than the practice ones you do?  Thanks.",
   'Hi @techTFQ , your explanation for complex SQL queries are superb... easily understandable. Plz make some videos on "Date Functions", "handling NULL values" , "System statistical function", "Cursors", Triggers". Thanks a lot for your helpful videos.',
   'When is your next cohort starting?',
   'when is your next bootcamp batch starting?',
   'When will you start your new boot camp ??',
   'Hi Sir, Could you please let me know when is the next batch starting? And will this include live projects or assignments?',
   'Hi, I have watched many of your videos, you teach in an excellent way!!!. Looking forward for the next bootcamp. Please let me know if any bootcamp starting in August soon after the current one? Already 12 classes are done, so looking for the new batch. Pls let me know. Thank you!',
   'Anyone who joined how is the experience so far?']},
 {'video_id': 'smztq8sRAhk',
  'comments': ['is that platform is free to use',
   'Please Make Vedio about python full course .',
   'Hi TFQ,\n\nI Want to learn python from binning, colud you please help me on this',
   'Sir, I want to learn advance SQL so please tell me how I can contact you',
   'i want to learn sql i send out email and message on insta 2 day before still waiting for reply i am shock u dont reply me so how you will reply message after enroll in program',
   'Sir but chat gpt aa gaya..ab kya learn karne ka fayeda h',
   'Could you plz recommend for pyspark as well',
   'Sir any video on sql',
   'can you make video on indexes  and partition in sql. \n\nTHANKS for resources on python.',
   'I am sure it will be a great platform, if you are saying it:) I like the LearnSQL platform a lot cuz of its ease and simplicity']},
 {'video_id': '7skZzocEU6c',
  'comments': ['OMG ur great...plz complete playlist of MYSQL plz ...',
   'Awesome',
   'what a beautiful solution to such a complex problem statement. I am mesmerized by your critical thinking and your approach. WOW! just WOW',
   'Awesome explanation ❤',
   'phenomenal solving approach ! Very helpful ! Thanks much',
   'how  to solve this question in oracle SQL\nplease exp.',
   'Thanks for this awesome video! Can you explain the difference between "RECURSIVE" and "OPEN CURSOR?"',
   'Great one bhai ek number',
   'Hi ,I need sql from basics to advanced level i can have the previous class videos and i will pay the nxt was on june 3rd but from nxt month onwards i have to do the work so if possible i will learn from this month onwards and i mailed you regarding this kindly rply me',
   'Hi thafiq \nCan you please explain about why table has skewed']},
 {'video_id': 'LZGaRcDxj8I',
  'comments': ['I tried same way however I don’t get the all hierarchy.. please help',
   'Make video for print type question in SQL',
   'Nice',
   'Hi Thoufiq! Your videos and playlists on SQL have been very helpful. I went through many of your videos before appearing for an interview this week and it came in very handy. Thanks for these videos. I was asked a question in interview today with a service based startup that a table is given called Trips: Trip_id ,rider_id, city_id, trip_timestamp (actual data was not given).  Question was Find users who have taken trips 5 consecutive days. I got an initial approach to use lag and then datediff to find difference between continuous trips but could not reach the final answer. Can you please help? Thanks in advance.',
   'Amazing',
   'Great',
   'Thanks again for the wonderful explanation.',
   'explanation is very next level Thank You Sir',
   'very well explained',
   'debugging iteration of recursive is amazing.']},
 {'video_id': 'rBPQ5fg_kiY',
  'comments': ["Very clearly explained the concept of Normalization. I was wondering how can the same be implied in there are hundreds of columns. You have manually added product code for duplicates in Relationships table but how's it possible to update if the data Is large. TIA!",
   'Amazing explanation and clarity. Thank you!',
   'Great video. Working through the example database helps a lot.',
   'Yes, the best video to understand Normalization. Thank you very much. Could you please upload a video on ER diagram in detail?',
   'Thank you, thank you so much for knowledge sharing with us in good understanding manner.\nI Love your content and your way of explanation too.',
   'thank you 😄',
   'Very well explained sir',
   'Very Very excellent.',
   "I have to say that I have made 3 courses with modules about data modeling and schemas, and this is the first time that I'm realling understanding how to build an ER Diagram. \n\nMany thanks for your explanation and all the best",
   'This was a lot of fun and very helpful! You did an excellent job! Liked and subscribed']},
 {'video_id': 'hvwltYazuQo',
  'comments': ['hi, when will next   sql bootcamp start',
   'bhai......you delivered awesome content but all videos had low sound,(laptop sound & youtube sound 100 still not audible at 2 ft) please fix it if possible.\ni tried to watch all sql viddeos but due to sound i cant make consistency',
   'When next live training will be available',
   'Hi @techTFQ , since the live classes are ended, can we have any discount to buy just the recorded videos? That would be great, if you can provide.',
   'Hi, when will the next sql bootcamp starts?',
   'When is the next sql boot camp?',
   'When is the next bootcamp?',
   'When is the next cohort',
   'Hi sir,  When will you start the next batch',
   'Will you be holding the boot camp again after? Or should I just purchase and watch them recorded.']},
 {'video_id': 'a-hFbr-4VQQ',
  'comments': ['Amazing video. The link to your website is not opening. Kindly help',
   'Thank you very much sir for this video 🙏 ☺️',
   'Where i find all this links',
   'thanks you so much',
   'Thank you so much sir, you have given a clear road map i was actually looking for this Thanks sir',
   'wow great job!!\nhighly recommend.',
   'I have lot of confusions on SQL ,now I am clear about SQL thank you for making clear roadmap .',
   'Thanks',
   'Seldom do you come across such an incredibly well structured and accurate video anywhere. Thank you af.',
   'Awesome sir!!!! Great job... This video tempts me to learn!!']},
 {'video_id': 'pMNcPLc9Z7c',
  'comments': ['Just Use either DECODE or CASE',
   "DECODE ( ID,    1, 'ROOT',    2,'INNER',  'LEAF') Type",
   'Brother I want to join your training sessions... please tell me the amount details',
   'Link : https://youtu.be/zZKb8FQRShs',
   'And this is why that is a stupid question to ask at an interview. Because in a real job situation they would have researched it with Google and quickly come up with a solution.',
   'Sir actually I just want to know  \n\nHow can I export my SQL data after shorting please let me know',
   'chatGPT is the solution 😇',
   "Solved this on leetcode. It's a simple select use case or union query.",
   'Thanks for sharing  I really liked the way you solve a query. I have one question that was asked in interview.\r\nthere is sequence of numbers in "ID" column of a table and it contains values as (1,2,3,50,51,56,60).\r\nso expected output should be like \r\ngaps_start       gaps_end\r\n----------------------------------------\r\n4                             49\r\n52                          55\r\n57                           59\r\n\r\nplease share your idea how to solve this.',
   '🎉']},
 {'video_id': 'zZKb8FQRShs',
  'comments': ['Your explanation is just too good....',
   "your solution is simpler than mine:\nselect id, 'root' as type\nfrom tree\nwhere p_id is null\nunion\nselect distinct p_id as id, 'inner' as type\nfrom tree\nwhere p_id <> (select id from tree where p_id is null) and p_id is not null\nunion\nselect id, 'leaf' as type\nfrom tree\nwhere id not in (select distinct p_id from tree where p_id is not null) and\n\t\tp_id is not null",
   'great thanks',
   'The way you explained the problem I really  stunned',
   'Excellent! Feeling a lot more prepared to take on interviews because of you!!!!',
   'Thank you bro for this solution !',
   'Thanks a lot for doing these kind of videos❤️',
   'Hi bro, I am working as a DBA since last 7 months and also following your channel since past few months, Just wanna say you Thanku for the Beautiful explanations and awesome videos on each topics.....Wonderful work.🙏',
   'Well explained 👏.  Made it easy',
   'Great Explanation']},
 {'video_id': 'jS5_hjFgfzA',
  'comments': ['We can create a cte with their customer name and number of time it comes in between 2019 to 2021 and then we can find the sum of the values for the years between 2019 and 2021 and then divide it by the count values which we get from cte and group by the customer names',
   "::decimal (only this part) isn't working in microsoft sql server..whats the other way of changing this avg_bill_amount into decimal?",
   "Here is much clean and simpler way:\nSELECT customer_name, AVG(billed_amount) AS average_billed_amount\nFROM billing\nWHERE billing_creation_date >= '2019-01-01' AND billing_creation_date <= '2021-12-31'\nGROUP BY customer_name;",
   "with prasad as\n(\nselect \n*,\nextract (year from billing_creation_date) as years\nfrom billing\nwhere billing_creation_date between '2019-01-01' and '2021-12-31'\n)\nselect \ncustomer_id,\nsum(billed_amount)/\n(case \n\twhen count(distinct years)=1 then count(years)+2 \n\twhen count(distinct years)=2 then count(years)+1\n\telse count(years)\nend) as billed_amount\nfrom prasad\ngroup by 1;",
   "I'm not clear about( with cte as) why we use this and   what for all  the queries we use the same statement. otherwise suggest me some other way",
   'PLEASE PROVIDE THE TABLE CREATION AND DATA INSERTAION QUERIES WHEN U DO SUCH KIND OF VIDEOS.THAT WILL HELP SAVE TIME',
   "I was able to solve before watching solution. Used a different method using row_number() to count additional payments in one year. Assumed every groups sum should be divided by 3 plus any additional payments. Basically just get the sum of all payments for group and then decide what to divide by.\n\n-- my solution\nselect customer_id,customer_name, \nconcat('$',cast(total_sales / cast(3 + additional_payments as decimal(5,2)) as decimal(5,2))) as avg_billing_amount\nfrom (\n\tselect distinct customer_id, customer_name, total_sales, \n\tmax(additional_payments) over (partition by customer_name) - 1 as additional_payments\n\tfrom (\n\t\tselect distinct customer_id,customer_name, \n\t\tsum(billed_amount) over (partition by customer_name ) as total_sales,\n\t\tmax(num_billing) over (partition by customer_name, Y order by y) as additional_payments\n\t\tfrom (\n\t\t\tselect customer_id,customer_name, billed_amount, y,\n\t\t\tROW_NUMBER() over (partition by customer_name, Y order by y) as num_billing\n\t\t\tfrom (\n\t\t\t\tselect *,\n\t\t\t\tyear(billing_creation_date) as y\n\t\t\t\tfrom billing\n\t\t\t\twhere billing_creation_date > '2019-01-01') X) z) q) n",
   '--SOLUTION 1 (simplest)\r\nSELECT\r\n\tDISTINCT c.CustomerName,\r\nAVG(b.billing_amount) OVER(PARTITION BY c.customerID ORDER BY c.customerID ) as AvgBill\r\nFROM\r\n[dbo].[billing] b\r\nINNER JOIN [dbo].[Customer] c on b.CustomerID = c.customerID\r\nWHERE datepart(year,b.[billing_creation_date]) > 2019\r\n\r\n--SOLUTION 2\r\nGO\r\nWith thisCTE\r\nas\r\n(\r\nSELECT\r\n\t c.CustomerName,\r\nAVG(b.billing_amount) as AvgBill\r\nFROM\r\n[dbo].[billing] b\r\nINNER JOIN [dbo].[Customer] c on b.CustomerID = c.customerID\r\nWHERE datepart(year,b.[billing_creation_date]) > 2019\r\nGROUP BY Rollup(c.CustomerName)\r\n)\r\nSELECT * FROM thisCTE\r\nWHERE CustomerName is not NULL',
   'Someone asked me to hold my ear so I ran my arm between my legs and froze it behind my head and grabbed my ear.',
   'can we use select *, avg(billing amount) from table name where date between 2019 and 2021 group by custmer name ;']},
 {'video_id': '6UAU79FNBjQ',
  'comments': ["Hey Thoufiq, I tried it this way.\n\nwith cte as (select account_no,transaction_date,debit_credit,case when debit_credit='debit' then transaction_amount*-1 else transaction_amount end as tr_amt from account_balance)\n, cte2 as (select *,sum(tr_amt) over (partition by account_no order by transaction_date) as running_sum,row_number() over (partition by account_no order by transaction_date desc) as rn from cte)\n, cte3 as (select account_no from cte2 where rn=1 and running_sum<1000)\n, cte4 as (select *,lag(running_sum) over (partition by account_no order by transaction_date) as lg from cte2 where account_no not in (select account_no from cte3))\nselect account_no,transaction_date from cte4 where (lg<1000 and running_sum>=1000) or (lg is null and running_sum>=1000)",
   "with original_file as (\r\n select account_no, transaction_date, case\r\n when debit_credit = 'debit' then transaction_amount * -1 else transaction_amount end transaction_amount\r\n  from account_balance\r\n ),\r\n\r\n credit_1 as (\r\n select account_no, transaction_date, transaction_amount,\r\n sum(transaction_amount) over (partition by account_no order by account_no) as amount_1\r\n from original_file\r\n )\r\n select credit_1.account_no, max(credit_1.transaction_date),  amount_1\r\n from credit_1\r\n where credit_1.amount_1 >=1000 and credit_1.transaction_amount >0\r\n group by credit_1.account_no, amount_1\r\n order by account_no",
   "with orignal_one as (\r\nselect account_no, debit_credit, transaction_date, \r\nsum(transaction_amount) over (partition by account_no, debit_credit order by account_no) as new_amount_trans\r\nfrom account_balance\r\n),\r\n\r\n\r\ncredit_1 as (\r\nselect account_no, max(transaction_date) as transaction_date, new_amount_trans\r\nfrom orignal_one\r\nwhere debit_credit = 'credit' and new_amount_trans >=1000\r\ngroup by account_no, new_amount_trans\r\n),\r\n\r\n\r\ndebit_1 as (\r\nselect account_no, transaction_date, new_amount_trans\r\nfrom orignal_one\r\nwhere debit_credit = 'debit'\r\n),\r\n\r\n\r\nfinal_table as (\r\nselect  credit_1.account_no, credit_1.transaction_date, case \r\nwhen credit_1.account_no = debit_1.account_no then credit_1.new_amount_trans - debit_1.new_amount_trans else credit_1.new_amount_trans \r\nend as new_one_amount\r\nfrom credit_1 \r\nleft join debit_1 on \r\ncredit_1.account_no = debit_1.account_no\r\n )\r\n\r\n select final_table.account_no, final_table.transaction_date \r\n from  final_table\r\n where new_one_amount >=1000",
   'what is the need to calculate final_balance column ? we can do  without it',
   'Wow',
   'Great teaching...! Thank you very much for sharing it sir.',
   "different data set and table structure..\n\n\r\ncreate table t3 (acc_id int, account_name varchar (100), transaction_Date date, debit_credit varchar(10), amount int);\r\n\r\ninsert into t3 values (1, 'A', '2021-01-01', 'credit', 10000);\r\ninsert into t3 values (1, 'A', '2021-01-02', 'debit', 5000);\r\ninsert into t3 values (1, 'A', '2021-01-03','credit', 10000);\r\ninsert into t3 values (1, 'A', '2021-01-04','debit', 5000);\r\ninsert into t3 values (1, 'A', '2021-01-05','debit', 10000);\r\n\r\ninsert into t3 values (2, 'B', '2021-02-01', 'credit', 10000);\r\ninsert into t3 values (2, 'B', '2021-02-02', 'credit', 5000);\r\ninsert into t3 values (2, 'B', '2021-02-03', 'debit', 10000);\r\ninsert into t3 values (2, 'B', '2021-02-04', 'credit', 5000);\r\n\r\ninsert into t3 values (3, 'C', '2021-03-01', 'credit', 10000);\r\ninsert into t3 values (3, 'C', '2021-03-02', 'debit', 2000);\r\ninsert into t3 values (3, 'C', '2021-03-03', 'credit', 10000);\r\ninsert into t3 values (3, 'C', '2021-03-04', 'debit', 5000);\r\n\r\nselect acc_id, transaction_date, cumi_total \r\nfrom (\r\n\twith cte as (\r\n\t\t\t\tselect acc_id, transaction_date, debit_credit, Amount, dr_cr_amt, sum(dr_cr_amt) over (partition by acc_id order by transaction_date) \r\n\t\t\t\tas cumi_total\r\n\t\t\t\tfrom (\r\n\t\t\t\t\t\t\t\tselect Amount * (case \r\n\t\t\t\t\t\t\t\t\t\t\twhen debit_credit = 'debit' then -1\r\n\t\t\t\t\t\t\t\t\t\t\telse 1\r\n\t\t\t\t\t\t\t\t\t   end) as dr_cr_Amt, *\r\n\t\t\t\t\t\t\tfrom t3) \r\n\t\t\t\torder by 1 asc, 2 asc)\r\n\tselect *, row_number() over(partition by acc_id order by transaction_date desc) as rnk\r\n\tfrom cte) x\r\nwhere x.rnk =  1\r\nand x.cumi_total > 1;",
   "alter table account_balance add column tx_amt int;\nupdate account_balance set tx_amt = -(transaction_amount) where debit_credit = 'debit';\nupdate account_balance set tx_amt = transaction_amount where debit_credit = 'credit';\nwith test as (select *, sum(tx_amt) over(partition by account_no order by transaction_date \n\t\t\t\t\t\t\t\t\t\t range between unbounded preceding and unbounded following) as cum_balance,\n\t\t\t  case when sum(tx_amt) over(partition by account_no order by transaction_date) >=1000 then \n\t\t\t\t\t\t\t  1 else 0 end as flag \n\t\t\t  from account_balance)\nselect test.account_no, min (transaction_date)\nfrom test\nwhere cum_balance >= 1000 \n\t\t\t  and flag =1 \ngroup by test.account_no;",
   'Thanks...',
   'Such an Informative video I just got the conceptual clarity I was looking for. Thanks  a lot TechTFQ......🙂']},
 {'video_id': 'ZwFfiadQB3k',
  'comments': ['Your tips on SQL has really improved my scripting skills in my line of work. Very practical examples. Thank you for the good work',
   'Great Explanation',
   'nice one',
   "can anyone tell what the application this guy using, I'm new here so I want to know",
   'Thank you and God bless you.',
   "We can solve it without using cte as well .Here is my solution (MySQL) : - \n\nSELECT\n\tsr.roll_no,\n    sl.student_name,\n    sl.class,\n    sl.section,\n\tSUM(CASE WHEN subject = 'Math' AND option_marked = correct_option THEN 1 ELSE 0 END) AS math_correct,\n\tSUM(CASE WHEN subject = 'Math' AND option_marked != correct_option AND option_marked != 'e' THEN 1 ELSE 0 END) AS math_wrong,\n\tSUM(CASE WHEN subject = 'Math' AND option_marked = 'e' THEN 1 ELSE 0 END) AS math_yet_to_learn,\n    SUM(CASE WHEN subject = 'Math' AND option_marked = correct_option THEN 1 ELSE 0 END) AS math_score,\n    ROUND(SUM(CASE WHEN subject = 'Math' AND option_marked = correct_option THEN 1 ELSE 0 END) * 100 / SUM(IF(subject = 'Math', 1, 0)),2) AS math_percentage,\n    SUM(CASE WHEN subject = 'Science' AND option_marked = correct_option THEN 1 ELSE 0 END) AS science_correct,\n\tSUM(CASE WHEN subject = 'Science' AND option_marked != correct_option AND option_marked != 'e' THEN 1 ELSE 0 END) AS science_wrong,\n\tSUM(CASE WHEN subject = 'Science' AND option_marked = 'e' THEN 1 ELSE 0 END) AS science_yet_to_learn,\n    SUM(CASE WHEN subject = 'Science' AND option_marked = correct_option THEN 1 ELSE 0 END) AS science_score,\n    ROUND(SUM(CASE WHEN subject = 'Science' AND option_marked = correct_option THEN 1 ELSE 0 END) * 100 / SUM(IF(subject = 'Science', 1, 0)),2) AS science_percentage\nFROM student_response AS sr\nINNER JOIN correct_answer AS ca ON sr.question_paper_code = ca.question_paper_code AND sr.question_number = ca.question_number\nINNER JOIN student_list AS sl ON sr.roll_no = sl.roll_no\nINNER JOIN question_paper_code AS qpc ON sr.question_paper_code = qpc.paper_code\nGROUP BY 1,2,3,4",

# alteration of video details

In [104]:
import pandas as pd
import numpy as np
from dateutil import parser
import isodate

# Data visualization libraries
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
#sns.set(style="darkgrid", color_codes=True)

# Google API
#from googleapiclient.discovery import build

In [127]:
video_details['publishedAt'] =  video_details['publishedAt'].apply(lambda x: parser.parse(x)) 
video_details['pushblishDayName'] = video_details['publishedAt'].apply(lambda x: x.strftime("%A"))

In [109]:
pip install isodate

Requirement already satisfied: isodate in c:\users\pranesh\anaconda3\lib\site-packages (0.6.1)
Requirement already satisfied: six in c:\users\pranesh\anaconda3\lib\site-packages (from isodate) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [128]:
#video_details=pd.DataFrame(video_df)
video_details

,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favouriteCount,commentCount,duration,definition,caption,durationSecs,pushblishDayName
0,9QDhesMz6eY,MY CYCLING SPOT,"""DESTINY- FIGHT FOR HUNGER"" | CYCLE RALLY | RO...",#mycyclingspot #coimbatore #cycling,None,2023-02-06 04:17:59+00:00,203,17,None,6,PT4M36S,hd,false,276.0,Monday
1,wgWKZOQVuP8,MY CYCLING SPOT,KURINJI FLOWER SEASON | NEELAKURINJI | STROBIL...,#kurinji #kurinjipoo #kurinjiflower #neelak...,None,2022-10-30 13:17:05+00:00,524,38,None,13,PT9M54S,hd,false,594.0,Sunday
2,NSrHj7w879Y,MY CYCLING SPOT,WILDLIFE AWARENESS CYCLE RALLY | WILDLIFE WEEK...,#wildlifeweek2022 #wildlife #cycling \nMusic...,None,2022-10-05 04:14:47+00:00,471,41,None,22,PT13M29S,hd,false,809.0,Wednesday
3,b-eSb-sG_6g,MY CYCLING SPOT,HEAVY TRAFFIC DUE TO HEAVY RAIN IN COIMBATORE,#coimbatore #rainfall #environment,None,2022-09-01 15:34:21+00:00,343,13,None,0,PT5M3S,hd,false,303.0,Thursday
4,pcBuTNEjhXo,MY CYCLING SPOT,Heavy Rain in Coimbatore | Cross cut Bridge | ...,#coimbatore #mycyclingspot #environment,None,2022-08-29 11:03:12+00:00,240,8,None,2,PT1M24S,hd,false,84.0,Monday
5,LWl58ol2eAI,MY CYCLING SPOT,VGP MARINE KINGDOM| INDIA'S FIRST WALKTHROUGH ...,#vgpmarinekingdom #vgp #vgpuniversalkingdom...,None,2022-08-26 17:27:05+00:00,244,28,None,12,PT18M21S,hd,false,1101.0,Friday
6,rkGreFSBcJc,MY CYCLING SPOT,PRE- HISTORIC ROCK ART OF TAMILNADU | KUMITHIP...,#mycyclingspot #coimbatore #kumithipathy #c...,None,2022-08-03 05:57:28+00:00,246,28,None,21,PT7M11S,hd,false,431.0,Wednesday
7,7TcycHW53TA,MY CYCLING SPOT,PATHIMALAI BALAMURUGAN TEMPLE | 2000 YEARS OLD...,#mycyclingspot #pathimalaibalamurugantemple ...,None,2022-07-27 04:53:34+00:00,841,63,None,20,PT11M28S,hd,false,688.0,Wednesday
8,C7HlhmYnMvk,MY CYCLING SPOT,BICYCLE LIGHT | B-TWIN FL 920 | REVIEW | MY CY...,#mycyclingspot #cycling #coimbatore,None,2022-07-26 06:00:18+00:00,503,27,None,10,PT6M2S,hd,false,362.0,Tuesday
9,v4tYtbI19oM,MY CYCLING SPOT,COIMBATORE TO SITHANKUTTAI | BHAVANI SAGAR DAM...,#mycyclingspot #sithankuttai #sirumugai #cy...,None,2022-07-20 10:45:28+00:00,1610,67,None,27,PT13M1S,hd,false,781.0,Wednesday
10,bQFpNS1Yy5Q,MY CYCLING SPOT,ANUVAVI TEMPLE - TOP VIEW | CHINNATHADAGAM | M...,#mycyclingspot #cycling #coimbatore #anuvav...,None,2022-07-08 10:21:43+00:00,144,10,None,1,PT42S,hd,false,42.0,Friday
11,EvUbefDUMzM,MY CYCLING SPOT,CHITHIRAI CHAVADI | COIMBATORE | JULY 2022,#mycyclingspot #chithiraichavadi #coimbatore...,None,2022-07-05 12:23:34+00:00,569,23,None,3,PT1M20S,hd,false,80.0,Tuesday
12,f-T1P32Yn7k,MY CYCLING SPOT,COIMBATORE TO MALAMPUZHA DAM CYCLING| PALAKKAD...,#cookoocyclingclub #mycyclingspot #cycling,None,2022-06-30 04:09:09+00:00,1037,68,None,22,PT13M24S,hd,false,804.0,Thursday
13,XyWAb9pBorw,MY CYCLING SPOT,ROCK BEACH | PROMENEDE BEACH | PONDICHERRY | M...,#pondicherry #rockbeach #mycyclingspot,None,2022-06-13 05:46:17+00:00,178,17,None,1,PT9M20S,hd,false,560.0,Monday
14,38l9gcdV-Y4,MY CYCLING SPOT,KURANGANI HILLS CYCLING | BODINAYAKANUR | THEN...,#kurangani #cycling #mycyclingspot,None,2022-06-10 06:27:12+00:00,434,40,None,10,PT8M10S,hd,false,490.0,Friday
15,9AzxI9IAwgQ,MY CYCLING SPOT,"One year of ""MY CYCLING SPOT"" | THANK YOU FOR ...",#cycling #mycyclingspot,None,2022-05-30 17:50:32+00:00,244,34,None,15,PT2M45S,hd,false,165.0,Monday
16,5l5b1pwqKck,MY CYCLING SPOT,CYCLING IN WESTERN VALLEY HILLS | BUNGALOW CLU...,#mycyclingspot #cycling #westernvalleyhills,None,2022-05-28 15:43:17+00:00,588,40,None,15,PT10M42S,hd,false,642.0,Saturday
17,7VrliyIrS7A,MY CYCLING SPOT,CYCLING TO PONNUTHU AMMAN TEMPLE | CHINNATHADA...,,None,2022-05-14 07:17:51+00:00,593,56,None,35,PT7M59S,hd,false,479.0,Saturday
18,2byX730yM4s,MY CYCLING SPOT,BACK TO CYCLING AFTER 3 MONTHS | MY CYCLING SPOT,#mycyclingspot #cycling,None,2022-05-07 04:47:52+00:00,181,30,None,13,PT1M6S,hd,false,66.0,Saturday
19,JEAyKUgJ-K0,MY CYCLING SPOT,ROADEO WARCRY 27.5 | REVIEW | BEST MTB CYCLE |...,#cycling #roadeo #mycyclingspot,None,2022-04-22 07:15:12+00:00,1883,47,None,21,PT3M41S,hd,false,221.0,Friday
20,Cg5s_sZSPLE,MY CYCLING SPOT,ELEPHANT 🐘 ADOBE BOATING | ANAYIRANGAL DAM| MU...,#munnar #anayirangal,None,2022-04-12 15:58:08+00:00,475,17,None,3,PT2M28S,hd,false,148.0,Tuesday
21,l6ZwpiOrOOE,MY CYCLING SPOT,MUNI PAARAI | BEAUTIFUL SPOT IN MUNNAR | CHINN...,CLIFFDOMICILE RESORT: http://www.cliffdomicile...,None,2022-04-05 05:38:08+00:00,801,74,None,18,PT15M21S,hd,false,921.0,Tuesday
22,br1B-uggM44,MY CYCLING SPOT,PONNUTHU AMMAN TEMPLE ADIVARAM | COIMBATORE | ...,#coimbatore #mycyclingspot #ponnuthuammant...,None,2022-02-04 17:12:54+00:00,591,53,None,34,PT9M29S,hd,false,569.0,Friday
23,3ekh7gYuLrM,MY CYCLING SPOT,ROADEO A575 | REVIEW | BEST MTB CYCLE FOR HILL...,#roadeo #cycling #mycyclingspot,None,2022-01-26 17:38:34+00:00,470,21,None,6,PT1M28S,hd,false,88.0,Wednesday
24,E_zcLdrtjpU,MY CYCLING SPOT,KUNIYAMUTHUR ANAIKATTU | MADAMPATTI | MY CYCLI...,#cycling #mycyclingspot,None,2022-01-04 17:08:35+00:00,394,24,None,0,PT1M43S,hd,false,103.0,Tuesday
25,lI5ztKBLpGc,MY CYCLING SPOT,"DINOSAUR EXHIBITION IN POLLACHI | UPTO JAN 30,...",#pollachi #kidsexhibition #dinosaurs #mycyc...,None,2022-01-03 03:13:09+00:00,489,16,None,0,PT3M47S,hd,false,227.0,Monday
26,l0ZLXp9JaRk,MY CYCLING SPOT,CYCLE RIDE TO ANAIKATTI | MY CYCLING SPOT | TAMIL,#cycling #mycyclingspot #anaikatti,None,2021-12-31 16:00:35+00:00,682,39,None,9,PT4M49S,hd,false,289.0,Friday
27,Aw4p_Xj6oiw,MY CYCLING SPOT,PUTHUKKADU ANAIKATTU | NARASIPURAM WATERFALLS ...,#mycyclingspot #coimbatore #narasipuram #cyc...,None,2021-12-18 09:22:45+00:00,2734,106,None,33,PT10M21S,hd,false,621.0,Saturday
28,_lR4wE7kOP8,MY CYCLING SPOT,UVARI BEACH | THISAYANVILAI TALUK | TIRUNELVEL...,#uvaribeach #tirunelveli,None,2021-12-16 07:23:45+00:00,3418,44,None,5,PT2M21S,hd,false,141.0,Thursday
29,rOOTUl1AvME,MY CYCLING SPOT,HERO SPRINT DORAN-29T | REVIEW | BEST MTB CYCL...,#cycling #mycyclingspot #herosprint,None,2021-12-10 14:35:08+00:00,1135,41,None,24,PT2M14S,hd,false,134.0,Friday
30,wa9Qutlri8Y,MY CYCLING SPOT,COIMBATORE TO KODIVERI DAM CYCLING | 160KM CYC...,#cycling #kodiveridam #sathyamangalam #coim...,None,2021-11-15 12:57:53+00:00,1250,73,None,38,PT15M37S,hd,false,937.0,Monday
31,vXKgnHl_R64,MY CYCLING SPOT,WHEN DOG CHASES CYCLIST... WHAT TO DO?? | MY C...,#cycling #mycyclingspot,None,2021-11-07 18:57:32+00:00,2916,87,None,26,PT5M19S,hd,false,319.0,Sunday
32,HrDCrrXw3Kc,MY CYCLING SPOT,🚴‍♂️***CYCLE RIDE - NATURE RIDE(3)***🚴‍♂️ | MY...,#cycling #mycyclingspot #environmentfriendly,None,2021-10-26 04:10:49+00:00,245,22,None,4,PT23S,hd,false,23.0,Tuesday
33,O3YBgikRmq8,MY CYCLING SPOT,BE CAREFUL WHILE CYCLING IN VILLAGE SIDE ROAD ...,,None,2021-10-24 07:18:34+00:00,323,33,None,7,PT38S,hd,false,38.0,Sunday
34,5KGiEeta83g,MY CYCLING SPOT,BUTTERFLY 🦋 GARDEN IN NILGIRI BIOSPHERE NATURE...,#nilgiribiospherenaturepark #anaikatti #co...,None,2021-09-26 18:26:23+00:00,1241,63,None,23,PT6M2S,hd,false,362.0,Sunday
35,f6-7OFo61gU,MY CYCLING SPOT,Thank you Friends😍😍🙏🙏🙏 500+ Subscribers | MY C...,#mycyclingspot #cycling #environmentfriendly,None,2021-09-18 07:42:43+00:00,358,35,None,25,PT35S,hd,false,35.0,Saturday
36,nhSaXFZfFoc,MY CYCLING SPOT,MY FIRST NIGHT CYCLE RIDE | UKKADAM TO MARUTHA...,#cycling #maruthamalai #coimbatore #mycycli...,None,2021-09-11 08:44:11+00:00,533,49,None,24,PT5M32S,hd,false,332.0,Saturday
37,aSi3lC5bHds,MY CYCLING SPOT,HOW I REDUCED 10Kgs IN A MONTH BY CYCLING | MY...,#cycling #mycyclingspot #weightreduction \...,None,2021-09-10 15:10:36+00:00,686,65,None,16,PT5M50S,hd,false,350.0,Friday
38,4UAJ82ySk8I,MY CYCLING SPOT,BEST MTB/HYBRID CYCLES UNDER 10K & 15K & 20K |...,CYCLE & CYCLE CAREE :- https://maps.app.goo.gl...,None,2021-09-03 13:06:45+00:00,3313,132,None,34,PT9M18S,hd,false,558.0,Friday
39,G4cz_n9f50A,MY CYCLING SPOT,DIFFICULTY OF TAKING VIDEO IN CYCLE RIDE | MY ...,#cycling #staysafestayhealthy #environment...,None,2021-08-29 04:25:00+00:00,324,49,None,14,PT1M1S,hd,false,61.0,Sunday
40,7-uOmafYYsE,MY CYCLING SPOT,POLLACHI TO ALIYAR DAM ROAD in a Single Shot V...,#pollachi #aliyardam #valparairoad #coimb...,None,2021-08-28 08:28:12+00:00,1142,43,None,8,PT2M26S,hd,false,146.0,Saturday
41,SjEv1GMWNEs,MY CYCLING SPOT,COIMBATORE TO POLLACHI HIGHWAY | NH-83 | NEW H...,#coimbatore #pollachi #NH83 #coimbatoret...,None,2021-08-19 03:00:16+00:00,1960,48,None,6,PT1M55S,hd,false,115.0,Thursday
42,n8RukW0ZHrg,MY CYCLING SPOT,🚴***CYCLE RIDE - NATURE RIDE (2)***🚴 | MY CYCL...,#cycling #coimbatore #environment #mycyc...,None,2021-08-17 02:14:03+00:00,443,36,None,2,PT28S,hd,false,28.0,Tuesday
43,gElo4BaBRBA,MY CYCLING SPOT,MY FIRST LONG RIDE | FAILED RIDE | KOTHAGIRI H...,#cycling #kothagiri #ooty #coimbatore,None,2021-08-12 15:49:09+00:00,349,55,None,11,PT2M35S,hd,false,155.0,Thursday
44,2_2InqemKM8,MY CYCLING SPOT,VAIDEHI WATERFALLS | NARASIPURAM | COIMBATORE ...,#cycling #coimbatore #narasipuram #vaideh...,None,2021-08-11 15:03:02+00:00,5160,164,None,58,PT12M2S,hd,false,722.0,Wednesday
45,bFSJwISbKsY,MY CYCLING SPOT,BISCUIT CUP COFFEE/TEA | HAPPY BAKES & SWEETS ...,#cycling #coimbatore #happybakesandsweets ...,None,2021-08-09 09:50:33+00:00,1441,115,None,36,PT6M57S,hd,false,417.0,Monday
46,zw7zVrnb_3A,MY CYCLING SPOT,FUN MOMENTS WITH MY FRIENDS | VADIVELU VOICE M...,#cycling #coimbatore #noyyalriver,None,2021-08-08 06:10:53+00:00,400,44,None,7,PT1M6S,hd,false,66.0,Sunday
47,ZiD1z1FiKF0,MY CYCLING SPOT,"""KUNIYAMUTHUR ANAIKATTU"" | COIMBATORE | THONDA...",#coimbatore #cycling #mycyclingspot\n\nMAG...,None,2021-08-04 14:38:10+00:00,2410,67,None,25,PT5M37S,hd,true,337.0,Wednesday
48,SZjp5nRrjOs,MY CYCLING SPOT,MAGICAL SPOT FOR HIKERS & CYCLERS | COIMBATORE...,ONE RUPEE IDLY PATTI KADAI:- https://m.youtube...,None,2021-08-02 16:42:23+00:00,3122,156,None,69,PT8M44S,hd,false,524.0,Monday
49,EFglOC5hE4Y,MY CYCLING SPOT,ONE RUPEE IDLY PATTI KADAI | 80+ YEARS OLD GRA...,#mycyclingspot #coimbatore #cycling,None,2021-07-31 05:26:13+00:00,844,73,None,46,PT7M4S,hd,false,424.0,Saturday
50,j18m1H7h5wk,MY CYCLING SPOT,SAFETY PRECAUTIONS FOR CYCLE RIDERS | MY CYCLI...,#roadsafety #mycyclingspot #cycling #saf...,None,2021-07-28 08:27:47+00:00,652,61,None,31,PT5M30S,hd,false,330.0,Wednesday
51,fsGYoAIJn_U,MY CYCLING SPOT,OTHIMALAI UPHILL | A SHORT VIDEO | MY CYCLING ...,#othimalai #cycling #beautifulplaceincoimba...,None,2021-07-18 17:13:35+00:00,566,49,None,11,PT1M47S,hd,false,107.0,Sunday
52,xRrZQfVMEhI,MY CYCLING SPOT,🚴***CYCLE RIDE - NATURE RIDE***🚴 | MY CYCLING ...,#cycling #nature #environment\n\nFirst 100k...,None,2021-07-17 04:33:43+00:00,1079,53,None,7,PT23S,hd,false,23.0,Saturday
53,BK4IQakNEmE,MY CYCLING SPOT,COIMBATORE To OTHIMALAI CYCLING | FIRST 100KM ...,#naveenhaldorai #cycling #othimalai,None,2021-07-13 04:52:31+00:00,8547,368,None,110,PT20M39S,hd,false,1239.0,Tuesday
54,62jhIkV7dKs,MY CYCLING SPOT,"Cycling to ""ISHA"" | Adiyogi- The Source of YOG...",#cycling #ishayoga #adiyogi,None,2021-07-02 15:11:05+00:00,1032,96,None,74,PT14M59S,hd,true,899.0,Friday
55,s7GxfRtooDA,MY CYCLING SPOT,Stretches to do Before Cycling & After Cycling...,Long Ride Cycling is not so easy until we do s...,None,2021-05-30 13:24:34+00:00,2622,193,None,71,PT11M12S,hd,true,672.0,Sunday

In [131]:
video_details.dtypes

video_id                             object
channelTitle                         object
title                                object
description                          object
tags                                 object
publishedAt         datetime64[ns, tzutc()]
viewCount                            object
likeCount                            object
favouriteCount                       object
commentCount                         object
duration                             object
definition                           object
caption                              object
durationSecs                        float64
pushblishDayName                     object
dtype: object

In [130]:
video_details["publishedAt"].astype(str)

0     2023-02-06 04:17:59+00:00
1     2022-10-30 13:17:05+00:00
2     2022-10-05 04:14:47+00:00
3     2022-09-01 15:34:21+00:00
4     2022-08-29 11:03:12+00:00
5     2022-08-26 17:27:05+00:00
6     2022-08-03 05:57:28+00:00
7     2022-07-27 04:53:34+00:00
8     2022-07-26 06:00:18+00:00
9     2022-07-20 10:45:28+00:00
10    2022-07-08 10:21:43+00:00
11    2022-07-05 12:23:34+00:00
12    2022-06-30 04:09:09+00:00
13    2022-06-13 05:46:17+00:00
14    2022-06-10 06:27:12+00:00
15    2022-05-30 17:50:32+00:00
16    2022-05-28 15:43:17+00:00
17    2022-05-14 07:17:51+00:00
18    2022-05-07 04:47:52+00:00
19    2022-04-22 07:15:12+00:00
20    2022-04-12 15:58:08+00:00
21    2022-04-05 05:38:08+00:00
22    2022-02-04 17:12:54+00:00
23    2022-01-26 17:38:34+00:00
24    2022-01-04 17:08:35+00:00
25    2022-01-03 03:13:09+00:00
26    2021-12-31 16:00:35+00:00
27    2021-12-18 09:22:45+00:00
28    2021-12-16 07:23:45+00:00
29    2021-12-10 14:35:08+00:00
30    2021-11-15 12:57:53+00:00
31    2021-11-07 18:57:32+00:00
32    2021-10-26 04:10:49+00:00
33    2021-10-24 07:18:34+00:00
34    2021-09-26 18:26:23+00:00
35    2021-09-18 07:42:43+00:00
36    2021-09-11 08:44:11+00:00
37    2021-09-10 15:10:36+00:00
38    2021-09-03 13:06:45+00:00
39    2021-08-29 04:25:00+00:00
40    2021-08-28 08:28:12+00:00
41    2021-08-19 03:00:16+00:00
42    2021-08-17 02:14:03+00:00
43    2021-08-12 15:49:09+00:00
44    2021-08-11 15:03:02+00:00
45    2021-08-09 09:50:33+00:00
46    2021-08-08 06:10:53+00:00
47    2021-08-04 14:38:10+00:00
48    2021-08-02 16:42:23+00:00
49    2021-07-31 05:26:13+00:00
50    2021-07-28 08:27:47+00:00
51    2021-07-18 17:13:35+00:00
52    2021-07-17 04:33:43+00:00
53    2021-07-13 04:52:31+00:00
54    2021-07-02 15:11:05+00:00
55    2021-05-30 13:24:34+00:00
Name: publishedAt, dtype: object

In [95]:
video_df

NameError: name 'video_df' is not defined

In [115]:
# convert duration to seconds
import isodate
video_details['durationSecs'] = video_details['duration'].apply(lambda x: isodate.parse_duration(x))
video_details['durationSecs'] = video_details['durationSecs'].astype('timedelta64[s]')

In [117]:
final=video_details.to_dict()

In [101]:
pip install pymongo

Requirement already satisfied: pymongo in c:\users\pranesh\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\users\pranesh\anaconda3\lib\site-packages (from pymongo) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

In [118]:
final

{'video_id': {0: '9QDhesMz6eY',
  1: 'wgWKZOQVuP8',
  2: 'NSrHj7w879Y',
  3: 'b-eSb-sG_6g',
  4: 'pcBuTNEjhXo',
  5: 'LWl58ol2eAI',
  6: 'rkGreFSBcJc',
  7: '7TcycHW53TA',
  8: 'C7HlhmYnMvk',
  9: 'v4tYtbI19oM',
  10: 'bQFpNS1Yy5Q',
  11: 'EvUbefDUMzM',
  12: 'f-T1P32Yn7k',
  13: 'XyWAb9pBorw',
  14: '38l9gcdV-Y4',
  15: '9AzxI9IAwgQ',
  16: '5l5b1pwqKck',
  17: '7VrliyIrS7A',
  18: '2byX730yM4s',
  19: 'JEAyKUgJ-K0',
  20: 'Cg5s_sZSPLE',
  21: 'l6ZwpiOrOOE',
  22: 'br1B-uggM44',
  23: '3ekh7gYuLrM',
  24: 'E_zcLdrtjpU',
  25: 'lI5ztKBLpGc',
  26: 'l0ZLXp9JaRk',
  27: 'Aw4p_Xj6oiw',
  28: '_lR4wE7kOP8',
  29: 'rOOTUl1AvME',
  30: 'wa9Qutlri8Y',
  31: 'vXKgnHl_R64',
  32: 'HrDCrrXw3Kc',
  33: 'O3YBgikRmq8',
  34: '5KGiEeta83g',
  35: 'f6-7OFo61gU',
  36: 'nhSaXFZfFoc',
  37: 'aSi3lC5bHds',
  38: '4UAJ82ySk8I',
  39: 'G4cz_n9f50A',
  40: '7-uOmafYYsE',
  41: 'SjEv1GMWNEs',
  42: 'n8RukW0ZHrg',
  43: 'gElo4BaBRBA',
  44: '2_2InqemKM8',
  45: 'bFSJwISbKsY',
  46: 'zw7zVrnb_3A',
  47: 'ZiD1z1FiKF0',
  48: 'SZjp5nRrjOs',
  49: 'EFglOC5hE4Y',
  50: 'j18m1H7h5wk',
  51: 'fsGYoAIJn_U',
  52: 'xRrZQfVMEhI',
  53: 'BK4IQakNEmE',
  54: '62jhIkV7dKs',
  55: 's7GxfRtooDA'},
 'channelTitle': {0: 'MY CYCLING SPOT',
  1: 'MY CYCLING SPOT',
  2: 'MY CYCLING SPOT',
  3: 'MY CYCLING SPOT',
  4: 'MY CYCLING SPOT',
  5: 'MY CYCLING SPOT',
  6: 'MY CYCLING SPOT',
  7: 'MY CYCLING SPOT',
  8: 'MY CYCLING SPOT',
  9: 'MY CYCLING SPOT',
  10: 'MY CYCLING SPOT',
  11: 'MY CYCLING SPOT',
  12: 'MY CYCLING SPOT',
  13: 'MY CYCLING SPOT',
  14: 'MY CYCLING SPOT',
  15: 'MY CYCLING SPOT',
  16: 'MY CYCLING SPOT',
  17: 'MY CYCLING SPOT',
  18: 'MY CYCLING SPOT',
  19: 'MY CYCLING SPOT',
  20: 'MY CYCLING SPOT',
  21: 'MY CYCLING SPOT',
  22: 'MY CYCLING SPOT',
  23: 'MY CYCLING SPOT',
  24: 'MY CYCLING SPOT',
  25: 'MY CYCLING SPOT',
  26: 'MY CYCLING SPOT',
  27: 'MY CYCLING SPOT',
  28: 'MY CYCLING SPOT',
  29: 'MY CYCLING SPOT',
  30: 'MY CYCLING SPOT',
  31: 'MY CYCLING SPOT',
  32: 'MY CYCLING SPOT',
  33: 'MY CYCLING SPOT',
  34: 'MY CYCLING SPOT',
  35: 'MY CYCLING SPOT',
  36: 'MY CYCLING SPOT',
  37: 'MY CYCLING SPOT',
  38: 'MY CYCLING SPOT',
  39: 'MY CYCLING SPOT',
  40: 'MY CYCLING SPOT',
  41: 'MY CYCLING SPOT',
  42: 'MY CYCLING SPOT',
  43: 'MY CYCLING SPOT',
  44: 'MY CYCLING SPOT',
  45: 'MY CYCLING SPOT',
  46: 'MY CYCLING SPOT',
  47: 'MY CYCLING SPOT',
  48: 'MY CYCLING SPOT',
  49: 'MY CYCLING SPOT',
  50: 'MY CYCLING SPOT',
  51: 'MY CYCLING SPOT',
  52: 'MY CYCLING SPOT',
  53: 'MY CYCLING SPOT',
  54: 'MY CYCLING SPOT',
  55: 'MY CYCLING SPOT'},
 'title': {0: '"DESTINY- FIGHT FOR HUNGER" | CYCLE RALLY | ROTARACT CLUB OF COIMBATORE COMITO | MY CYCLING SPOT',
  1: 'KURINJI FLOWER SEASON | NEELAKURINJI | STROBILANTHES KUNTHIANA | KALLIPPARA HILLS  | MUNNAR',
  2: 'WILDLIFE AWARENESS CYCLE RALLY | WILDLIFE WEEK 2022 | TAMILNADU FOREST DEPARTMENT| COIMBATORE',
  3: 'HEAVY TRAFFIC DUE TO HEAVY RAIN IN COIMBATORE',
  4: 'Heavy Rain in Coimbatore | Cross cut Bridge | August 29, 2022',
  5: "VGP MARINE KINGDOM| INDIA'S FIRST WALKTHROUGH AQUARIAM | CHENNAI",
  6: 'PRE- HISTORIC ROCK ART OF TAMILNADU | KUMITHIPATHY | COIMBATORE | PATHIMALAI BALAMURUGAN TEMPLE',
  7: 'PATHIMALAI BALAMURUGAN TEMPLE | 2000 YEARS OLD TEMPLE | KUMITHIPATHY | MY CYCLING SPOT | COIMBATORE',
  8: 'BICYCLE LIGHT | B-TWIN FL 920 | REVIEW | MY CYCLING SPOT',
  9: 'COIMBATORE TO SITHANKUTTAI | BHAVANI SAGAR DAM VIEW POINT | SIRUMUGAI | MY CYCLING SPOT',
  10: 'ANUVAVI TEMPLE - TOP VIEW | CHINNATHADAGAM | MY CYCLING SPOT',
  11: 'CHITHIRAI CHAVADI | COIMBATORE | JULY 2022',
  12: 'COIMBATORE TO MALAMPUZHA DAM CYCLING| PALAKKAD| COOKOO CYCLING CLUB | MY CYCLING SPOT',
  13: 'ROCK BEACH | PROMENEDE BEACH | PONDICHERRY | MY CYCLING SPOT',
  14: 'KURANGANI HILLS CYCLING | BODINAYAKANUR | THENI | KOTTAKUDI RIVER | WESTERN GHATS | MY CYCLING SPOT',
  15: 'One year of "MY CYCLING SPOT" | THANK YOU FOR YOUR SUPPORT| KEEP SUPPORTING',
  16: 'CYCLING IN WESTERN VALLEY HILLS | BUNGALOW CLUB RESORT| THONDAMUTHUR | MY CYCLING SPOT',
  17: 'CYCLING TO PONNUTHU AMMAN TEMPLE | CHINNATHADAGAM | KURUDIMALAI | MY CYCLING SPOT | COIMBATORE',
  18: 'BACK TO CYCLING AFTER 3 MONTHS | MY CYCLING SPOT',
  19: 'ROADEO WARCRY 27.5 | REVIEW | BEST MTB CYCLE | 2020 MODEL | MY CYCLING SPOT',
  20: 'ELEPHANT 🐘 ADOBE BOATING | ANAYIRANGAL DAM| MUNNAR',
  21: 'MUNI PAARAI | BEAUTIFUL SPOT IN MUNNAR | CHINNAKANAL | CLIFFDOMICILE RESORT',
  22: 'PONNUTHU AMMAN TEMPLE ADIVARAM | COIMBATORE | BEST PLACE FOR CYCLING | BEST TOURIST PLACE',
  23: 'ROADEO A575 | REVIEW | BEST MTB CYCLE FOR HILL RIDING | MY CYCLING SPOT',
  24: 'KUNIYAMUTHUR ANAIKATTU | MADAMPATTI | MY CYCLING SPOT',
  25: 'DINOSAUR EXHIBITION IN POLLACHI | UPTO JAN 30,2022 | OPPOSITE TO MURUGAN MARRIAGE HALL',
  26: 'CYCLE RIDE TO ANAIKATTI | MY CYCLING SPOT | TAMIL',
  27: 'PUTHUKKADU ANAIKATTU | NARASIPURAM WATERFALLS NEAR  ISHA | UNKNOWN PLACE IN COIMBATORE',
  28: 'UVARI BEACH | THISAYANVILAI TALUK | TIRUNELVELI DISTRICT | TAMILNADU',
  29: 'HERO SPRINT DORAN-29T | REVIEW | BEST MTB CYCLE | MY CYCLING SPOT | TAMIL',
  30: 'COIMBATORE TO KODIVERI DAM CYCLING | 160KM CYCLING | MY CYCLING SPOT | TAMIL',
  31: 'WHEN DOG CHASES CYCLIST... WHAT TO DO?? | MY CYCLING SPOT | TAMIL',
  32: '🚴\u200d♂️***CYCLE RIDE - NATURE RIDE(3)***🚴\u200d♂️ | MY CYCLING SPOT',
  33: 'BE CAREFUL WHILE CYCLING IN VILLAGE SIDE ROAD | MY CYCLING SPOT | 🐍😱| COIMBATORE',
  34: 'BUTTERFLY 🦋 GARDEN IN NILGIRI BIOSPHERE NATURE PARK | ANAIKATTI | COIMBATORE',
  35: 'Thank you Friends😍😍🙏🙏🙏 500+ Subscribers | MY CYCLING SPOT',
  36: 'MY FIRST NIGHT CYCLE RIDE | UKKADAM TO MARUTHAMALAI |25KM CYCLING | MY CYCLING SPOT | TAMIL',
  37: 'HOW I REDUCED 10Kgs IN A MONTH BY CYCLING | MY CYCLING SPOT | TAMIL',
  38: 'BEST MTB/HYBRID CYCLES UNDER 10K & 15K & 20K | CYCLE & CYCLE CAREE | MY CYCLING SPOT | TAMIL',
  39: 'DIFFICULTY OF TAKING VIDEO IN CYCLE RIDE | MY CYCLING SPOT | TAMIL    #Shorts',
  40: 'POLLACHI TO ALIYAR DAM ROAD in a Single Shot Video | BEAUTY OF POLLACHI | MY CYCLING SPOT',
  41: 'COIMBATORE TO POLLACHI HIGHWAY | NH-83 | NEW HIGHWAY | MY CYCLING SPOT',
  42: '🚴***CYCLE RIDE - NATURE RIDE (2)***🚴 | MY CYCLING SPOT',
  43: 'MY FIRST LONG RIDE | FAILED RIDE | KOTHAGIRI HILLS | NOV 2019 | MY CYCLING SPOT | TAMIL',
  44: 'VAIDEHI WATERFALLS | NARASIPURAM | COIMBATORE | MY CYCLING SPOT | TAMIL',
  45: 'BISCUIT CUP COFFEE/TEA | HAPPY BAKES & SWEETS | SIRUVANI ROAD | BOLUVAMPATTI | MY CYCLING SPOT',
  46: 'FUN MOMENTS WITH MY FRIENDS | VADIVELU VOICE MEMES | COIMBATORE | NOYYAL RIVER | MY CYCLING SPOT',
  47: '"KUNIYAMUTHUR ANAIKATTU" | COIMBATORE | THONDAMUTHUR -MADAMPATTI RD | NOYYAL RIVER | MY CYCLING SPOT',
  48: 'MAGICAL SPOT FOR HIKERS & CYCLERS | COIMBATORE  | BOLUVAMPATTI | SIRUVANI ROAD | MY CYCLING SPOT',
  49: 'ONE RUPEE IDLY PATTI KADAI | 80+ YEARS OLD GRANNY | MORNING CYCLING + BREAKFAST | MY CYCLING SPOT',
  50: 'SAFETY PRECAUTIONS FOR CYCLE RIDERS | MY CYCLING SPOT | TAMIL',
  51: 'OTHIMALAI UPHILL | A SHORT VIDEO | MY CYCLING SPOT',
  52: '🚴***CYCLE RIDE - NATURE RIDE***🚴 | MY CYCLING SPOT',
  53: 'COIMBATORE To OTHIMALAI CYCLING | FIRST 100KM CYCLE RIDE | MY CYCLING SPOT | TAMIL',
  54: 'Cycling to "ISHA" | Adiyogi- The Source of YOGA | A Mini Adventure Cycling | MY CYCLING SPOT | TAMIL',
  55: 'Stretches to do Before Cycling & After Cycling |  My Cycling Spot | Tamil'},
 'description': {0: '#mycyclingspot  #coimbatore  #cycling',
  1: '#kurinji  #kurinjipoo  #kurinjiflower  #neelakurinji  #strobilantheskunthiana  #munnar  #kallippara  #poopaara  #westernghats',
  2: '#wildlifeweek2022  #wildlife  #cycling \nMusic from Uppbeat (free for Creators!):\nhttps://uppbeat.io/t/paul-yudin/at-the-hotel\nLicense code: SGXKNTUBCBU96Z8Z',
  3: '#coimbatore  #rainfall  #environment',
  4: '#coimbatore  #mycyclingspot  #environment',
  5: '#vgpmarinekingdom   #vgp  #vgpuniversalkingdom  #aquarium  #aquariumfish   #fish  \n\nThe Marine Kingdom is the fourth in the many kingdoms unveiled by VGP. This is India’s first and largest walk-through aquarium housing everything from small to big aquatic animals. The animals here are housed in life-size tanks and over-head aquariums to give you a larger-than-life experience. So welcome to VGP Marine Kingdom, and while you are here, don’t forget to meet the sharks. \n\nWhat can we do in VGP marine kingdom?\nUnderwater Suite.\nUnderwater aquarium.\nSurprise Parties.\nScuba Diving.\nPrivate candlelight dinner.\nLive Feeding Show.',
  6: '#mycyclingspot #coimbatore   #kumithipathy  #cycling  #pathimalaibalamurugantemple  #pathimalai\n\nPathimalai Balamurugan Temple, 2000 years old temple:https://m.youtube.com/watch?v=7TcycHW53TA',
  7: '#mycyclingspot  #pathimalaibalamurugantemple  #coimbatore  #cycling',
  8: '#mycyclingspot  #cycling  #coimbatore',
  9: '#mycyclingspot  #sithankuttai  #sirumugai  #cycling \n\nSithankuttai -Dam view point:- https://www.google.co.in/search?q=sithankuttai+view+point&sxsrf=ALiCzsZm4A4joDCmLD1dw6DfpNwaxf3ljg%3A1658315326564&source=hp&ei=PuLXYq7-H__Tz7sP-7GvkAo&oq=sitha&gs_lcp=ChFtb2JpbGUtZ3dzLXdpei1ocBABGAEyBAgjECcyBAgjECcyBAgjECcyCwguEIAEELEDEIMBMggILhCABBCxAzIFCAAQgAQyBQguEIAEMgUILhCABDoHCCMQ6gIQJzoNCC4QxwEQrwEQ6gIQJzoLCAAQgAQQsQMQgwE6CAgAELEDEIMBOhEILhCABBCxAxCDARDHARDRAzoICAAQgAQQsQM6DgguEIAEEMcBEK8BENQCULgHWN4SYK0faABwAHgAgAHgAYgBoQiSAQUwLjQuMpgBAKABAbABDw&sclient=mobile-gws-wiz-hp\n\nCoimbatore to othimalai cycling:-  https://m.youtube.com/watch?v=BK4IQakNEmE',
  10: '#mycyclingspot  #cycling  #coimbatore  #anuvavitemple',
  11: '#mycyclingspot  #chithiraichavadi  #coimbatore  #cycling',
  12: '#cookoocyclingclub  #mycyclingspot  #cycling',
  13: '#pondicherry   #rockbeach  #mycyclingspot',
  14: '#kurangani  #cycling  #mycyclingspot',
  15: '#cycling   #mycyclingspot',
  16: '#mycyclingspot  #cycling   #westernvalleyhills',
  17: '',
  18: '#mycyclingspot  #cycling',
  19: '#cycling  #roadeo  #mycyclingspot',
  20: '#munnar   #anayirangal',
  21: 'CLIFFDOMICILE RESORT: http://www.cliffdomicile.co.in/\n\nMobile: 95781-21555\n\nUNESCO HERITAGE SITE IN MUNNAR:-\n1) MARAYOOR\n2) MUNIYARA DOLMENS\n3) KANNAN DEVAN TEA MUSEUM\n4) TEA PLANTATIONS',
  22: '#coimbatore   #mycyclingspot   #ponnuthuammantemple',
  23: '#roadeo  #cycling  #mycyclingspot',
  24: '#cycling   #mycyclingspot',
  25: '#pollachi  #kidsexhibition  #dinosaurs  #mycyclingspot',
  26: '#cycling   #mycyclingspot   #anaikatti',
  27: '#mycyclingspot  #coimbatore  #narasipuram #cycling \n\nPuthukkadu Anaikattu :- https://maps.app.goo.gl/Vy4jKjxD2tBwjM5U6',
  28: '#uvaribeach  #tirunelveli',
  29: '#cycling  #mycyclingspot   #herosprint',
  30: '#cycling  #kodiveridam  #sathyamangalam  #coimbatore',
  31: '#cycling   #mycyclingspot',
  32: '#cycling   #mycyclingspot   #environmentfriendly',
  33: '',
  34: '#nilgiribiospherenaturepark   #anaikatti   #coimbatore   #butterflygarden   #mycyclingspot',
  35: '#mycyclingspot   #cycling   #environmentfriendly',
  36: '#cycling  #maruthamalai  #coimbatore  #mycyclingspot\n\nInstagram ID:- "My_Cycling_Spot"\n\nFacebook Page: My Cycling Spot',
  37: '#cycling  #mycyclingspot   #weightreduction  \n\nInstagram ID:- "My_Cycling_Spot"\n\nFacebook page:- My Cycling Spot\n\nWhatsapp Group:- https://chat.whatsapp.com/HM4HGgAMGKl9O309WpaV7v',
  38: 'CYCLE & CYCLE CAREE :- https://maps.app.goo.gl/6briRTiChDdmX7pm6\n\nContact number:- 07339003339',
  39: '#cycling   #staysafestayhealthy   #environment   #safety   #healthy',
  40: '#pollachi  #aliyardam   #valparairoad   #coimbatore',
  41: '#coimbatore   #pollachi   #NH83   #coimbatoretopollachihighway',
  42: '#cycling   #coimbatore   #environment   #mycyclingspot      #environmentfriendly\n\nCYCLE RIDE - NATURE RIDE (1):- https://m.youtube.com/watch?v=xRrZQfVMEhI',
  43: '#cycling   #kothagiri   #ooty   #coimbatore',
  44: '#cycling   #coimbatore   #narasipuram  #vaidehiwaterfalls\n\nLocation :- https://g.co/kgs/fzt1Bj',
  45: '#cycling   #coimbatore   #happybakesandsweets   #boluvampatti   #siruvaniroad  #biscuitcupcoffee  #biscuitcuptea\n\nCHITHIRAI CHAVADI ANAIKATTU:- https://m.youtube.com/watch?v=8F5eoRfxuTE\n\nKUNIYAMUTHUR ANAIKATTU:- https://m.youtube.com/watch?v=ZiD1z1FiKF0\n\nMAGICAL SPOT FOR HIKERS & CYCLERS:- https://m.youtube.com/watch?v=SZjp5nRrjOs\n\nONE RUPEE IDLY PATTI KADAI:- https://m.youtube.com/watch?v=EFglOC5hE4Y\n\nCYCLING TO ISHA:- https://m.youtube.com/watch?v=62jhIkV7dKs&t=8s',
  46: '#cycling   #coimbatore   #noyyalriver',
  47: '#coimbatore   #cycling   #mycyclingspot\n\nMAGICAL SPOT FOR HIKERS & CYCLERS:- https://m.youtube.com/watch?v=SZjp5nRrjOs&pp=sAQA\n\nONE RUPEE IDLY PATTI KADAI:- https://m.youtube.com/watch?v=EFglOC5hE4Y&pp=sAQA\n\nCYCLING TO PATHIMALAI BALAMURUGAN TEMPLE:- https://m.youtube.com/watch?v=4KW3ybneFhk&pp=sAQA\n\nCOIMBATORE TO OTHIMALAI CYCLING:- https://m.youtube.com/watch?v=BK4IQakNEmE&pp=sAQA',
  48: 'ONE RUPEE IDLY PATTI KADAI:- https://m.youtube.com/watch?v=EFglOC5hE4Y&pp=sAQA\n\n#coimbatore   #mycyclingspot   #cycling',
  49: '#mycyclingspot   #coimbatore   #cycling',
  50: '#roadsafety   #mycyclingspot   #cycling   #safetyprecautionsforcycleriders',
  51: '#othimalai  #cycling   #beautifulplaceincoimbatore\n\nCOIMBATORE TO OTHIMALAI CYCLING: https://www.youtube.com/watch?v=BK4IQakNEmE&t=96s\n\nANUVAVI SUBRAMANIAN SWAMY TEMPLE CYCLING: https://www.youtube.com/watch?v=uONaTywa5o4&t=71s\n\nISHA- ADIYOGI-THE SOURCE OF YOGA CYCLING:https://www.youtube.com/watch?v=62jhIkV7dKs',
  52: '#cycling   #nature  #environment\n\nFirst 100km cycle Ride https://m.youtube.com/watch?v=BK4IQakNEmE',
  53: '#naveenhaldorai   #cycling    #othimalai',
  54: '#cycling    #ishayoga    #adiyogi',
  55: 'Long Ride Cycling is not so easy until we do some Basic Workouts..\nIn this video i ll say,\n1) workouts Before Cycling\n2) workouts After Cycling\n3) Necessary workouts for cyclers..\n\n\n#fitness    #workouts   #cycling'},
 'tags': {0: None,
  1: None,
  2: None,
  3: None,
  4: None,
  5: None,
  6: None,
  7: None,
  8: None,
  9: None,
  10: None,
  11: None,
  12: None,
  13: None,
  14: None,
  15: None,
  16: None,
  17: None,
  18: None,
  19: None,
  20: None,
  21: None,
  22: None,
  23: None,
  24: None,
  25: None,
  26: None,
  27: None,
  28: None,
  29: None,
  30: None,
  31: None,
  32: None,
  33: None,
  34: None,
  35: None,
  36: None,
  37: None,
  38: None,
  39: None,
  40: None,
  41: None,
  42: None,
  43: None,
  44: None,
  45: None,
  46: None,
  47: None,
  48: None,
  49: None,
  50: None,
  51: None,
  52: None,
  53: None,
  54: None,
  55: None},
 'publishedAt': {0: '2023-02-06T04:17:59Z',
  1: '2022-10-30T13:17:05Z',
  2: '2022-10-05T04:14:47Z',
  3: '2022-09-01T15:34:21Z',
  4: '2022-08-29T11:03:12Z',
  5: '2022-08-26T17:27:05Z',
  6: '2022-08-03T05:57:28Z',
  7: '2022-07-27T04:53:34Z',
  8: '2022-07-26T06:00:18Z',
  9: '2022-07-20T10:45:28Z',
  10: '2022-07-08T10:21:43Z',
  11: '2022-07-05T12:23:34Z',
  12: '2022-06-30T04:09:09Z',
  13: '2022-06-13T05:46:17Z',
  14: '2022-06-10T06:27:12Z',
  15: '2022-05-30T17:50:32Z',
  16: '2022-05-28T15:43:17Z',
  17: '2022-05-14T07:17:51Z',
  18: '2022-05-07T04:47:52Z',
  19: '2022-04-22T07:15:12Z',
  20: '2022-04-12T15:58:08Z',
  21: '2022-04-05T05:38:08Z',
  22: '2022-02-04T17:12:54Z',
  23: '2022-01-26T17:38:34Z',
  24: '2022-01-04T17:08:35Z',
  25: '2022-01-03T03:13:09Z',
  26: '2021-12-31T16:00:35Z',
  27: '2021-12-18T09:22:45Z',
  28: '2021-12-16T07:23:45Z',
  29: '2021-12-10T14:35:08Z',
  30: '2021-11-15T12:57:53Z',
  31: '2021-11-07T18:57:32Z',
  32: '2021-10-26T04:10:49Z',
  33: '2021-10-24T07:18:34Z',
  34: '2021-09-26T18:26:23Z',
  35: '2021-09-18T07:42:43Z',
  36: '2021-09-11T08:44:11Z',
  37: '2021-09-10T15:10:36Z',
  38: '2021-09-03T13:06:45Z',
  39: '2021-08-29T04:25:00Z',
  40: '2021-08-28T08:28:12Z',
  41: '2021-08-19T03:00:16Z',
  42: '2021-08-17T02:14:03Z',
  43: '2021-08-12T15:49:09Z',
  44: '2021-08-11T15:03:02Z',
  45: '2021-08-09T09:50:33Z',
  46: '2021-08-08T06:10:53Z',
  47: '2021-08-04T14:38:10Z',
  48: '2021-08-02T16:42:23Z',
  49: '2021-07-31T05:26:13Z',
  50: '2021-07-28T08:27:47Z',
  51: '2021-07-18T17:13:35Z',
  52: '2021-07-17T04:33:43Z',
  53: '2021-07-13T04:52:31Z',
  54: '2021-07-02T15:11:05Z',
  55: '2021-05-30T13:24:34Z'},
 'viewCount': {0: '203',
  1: '524',
  2: '471',
  3: '343',
  4: '240',
  5: '244',
  6: '246',
  7: '841',
  8: '503',
  9: '1610',
  10: '144',
  11: '569',
  12: '1037',
  13: '178',
  14: '434',
  15: '244',
  16: '588',
  17: '593',
  18: '181',
  19: '1883',
  20: '475',
  21: '801',
  22: '591',
  23: '470',
  24: '394',
  25: '489',
  26: '682',
  27: '2734',
  28: '3418',
  29: '1135',
  30: '1250',
  31: '2916',
  32: '245',
  33: '323',
  34: '1241',
  35: '358',
  36: '533',
  37: '686',
  38: '3313',
  39: '324',
  40: '1142',
  41: '1960',
  42: '443',
  43: '349',
  44: '5160',
  45: '1441',
  46: '400',
  47: '2410',
  48: '3122',
  49: '844',
  50: '652',
  51: '566',
  52: '1079',
  53: '8547',
  54: '1032',
  55: '2622'},
 'likeCount': {0: '17',
  1: '38',
  2: '41',
  3: '13',
  4: '8',
  5: '28',
  6: '28',
  7: '63',
  8: '27',
  9: '67',
  10: '10',
  11: '23',
  12: '68',
  13: '17',
  14: '40',
  15: '34',
  16: '40',
  17: '56',
  18: '30',
  19: '47',
  20: '17',
  21: '74',
  22: '53',
  23: '21',
  24: '24',
  25: '16',
  26: '39',
  27: '106',
  28: '44',
  29: '41',
  30: '73',
  31: '87',
  32: '22',
  33: '33',
  34: '63',
  35: '35',
  36: '49',
  37: '65',
  38: '132',
  39: '49',
  40: '43',
  41: '48',
  42: '36',
  43: '55',
  44: '164',
  45: '115',
  46: '44',
  47: '67',
  48: '156',
  49: '73',
  50: '61',
  51: '49',
  52: '53',
  53: '368',
  54: '96',
  55: '193'},
 'favouriteCount': {0: None,
  1: None,
  2: None,
  3: None,
  4: None,
  5: None,
  6: None,
  7: None,
  8: None,
  9: None,
  10: None,
  11: None,
  12: None,
  13: None,
  14: None,
  15: None,
  16: None,
  17: None,
  18: None,
  19: None,
  20: None,
  21: None,
  22: None,
  23: None,
  24: None,
  25: None,
  26: None,
  27: None,
  28: None,
  29: None,
  30: None,
  31: None,
  32: None,
  33: None,
  34: None,
  35: None,
  36: None,
  37: None,
  38: None,
  39: None,
  40: None,
  41: None,
  42: None,
  43: None,
  44: None,
  45: None,
  46: None,
  47: None,
  48: None,
  49: None,
  50: None,
  51: None,
  52: None,
  53: None,
  54: None,
  55: None},
 'commentCount': {0: '6',
  1: '13',
  2: '22',
  3: '0',
  4: '2',
  5: '12',
  6: '21',
  7: '20',
  8: '10',
  9: '27',
  10: '1',
  11: '3',
  12: '22',
  13: '1',
  14: '10',
  15: '15',
  16: '15',
  17: '35',
  18: '13',
  19: '21',
  20: '3',
  21: '18',
  22: '34',
  23: '6',
  24: '0',
  25: '0',
  26: '9',
  27: '33',
  28: '5',
  29: '24',
  30: '38',
  31: '26',
  32: '4',
  33: '7',
  34: '23',
  35: '25',
  36: '24',
  37: '16',
  38: '34',
  39: '14',
  40: '8',
  41: '6',
  42: '2',
  43: '11',
  44: '58',
  45: '36',
  46: '7',
  47: '25',
  48: '69',
  49: '46',
  50: '31',
  51: '11',
  52: '7',
  53: '110',
  54: '74',
  55: '71'},
 'duration': {0: 'PT4M36S',
  1: 'PT9M54S',
  2: 'PT13M29S',
  3: 'PT5M3S',
  4: 'PT1M24S',
  5: 'PT18M21S',
  6: 'PT7M11S',
  7: 'PT11M28S',
  8: 'PT6M2S',
  9: 'PT13M1S',
  10: 'PT42S',
  11: 'PT1M20S',
  12: 'PT13M24S',
  13: 'PT9M20S',
  14: 'PT8M10S',
  15: 'PT2M45S',
  16: 'PT10M42S',
  17: 'PT7M59S',
  18: 'PT1M6S',
  19: 'PT3M41S',
  20: 'PT2M28S',
  21: 'PT15M21S',
  22: 'PT9M29S',
  23: 'PT1M28S',
  24: 'PT1M43S',
  25: 'PT3M47S',
  26: 'PT4M49S',
  27: 'PT10M21S',
  28: 'PT2M21S',
  29: 'PT2M14S',
  30: 'PT15M37S',
  31: 'PT5M19S',
  32: 'PT23S',
  33: 'PT38S',
  34: 'PT6M2S',
  35: 'PT35S',
  36: 'PT5M32S',
  37: 'PT5M50S',
  38: 'PT9M18S',
  39: 'PT1M1S',
  40: 'PT2M26S',
  41: 'PT1M55S',
  42: 'PT28S',
  43: 'PT2M35S',
  44: 'PT12M2S',
  45: 'PT6M57S',
  46: 'PT1M6S',
  47: 'PT5M37S',
  48: 'PT8M44S',
  49: 'PT7M4S',
  50: 'PT5M30S',
  51: 'PT1M47S',
  52: 'PT23S',
  53: 'PT20M39S',
  54: 'PT14M59S',
  55: 'PT11M12S'},
 'definition': {0: 'hd',
  1: 'hd',

# alteration ending

# final data pushing

In [195]:
def main(channel_id):
    channel_details = get_channel_stats(youtube,channel_id)
    video_ids= get_video_ids(youtube,playlist_id)
    video_df=get_video_details(youtube, video_ids)
    comment_df=get_comments_in_videos(youtube, video_ids)
    data = {'channel_details' : channel_details,
            'video_ids' : video_ids,
            'video_details' : video_df,
            'comment_details' : comment_df
               }
    return data

In [211]:
type(data)

dict

In [202]:
#channel_details = get_channel_stats(youtube,channel_id)
#video_ids= get_video_ids(youtube,playlist_id)
#video_df=get_video_details(youtube, video_ids[0])
#comment_df=get_comments_in_videos(youtube, video_ids[0])
data = {'channel_details' : channel_details,
            'video_ids' : video_ids,
            'video_details' : video_df,
            'comment_details' : comment_df
               }
print(data)

{'channel_details': {'Channel_name': 'techTFQ', 'Subscribers': '218000', 'Views': '10913123', 'Total_videos': '89'}, 'video_ids': ['0QcEqFrhb_Y', 'smztq8sRAhk', '7skZzocEU6c', 'LZGaRcDxj8I', 'rBPQ5fg_kiY', 'hvwltYazuQo', 'a-hFbr-4VQQ', 'pMNcPLc9Z7c', 'zZKb8FQRShs', 'jS5_hjFgfzA', '6UAU79FNBjQ', 'ZwFfiadQB3k', 'Det4ZjBSe3M', 'xUsY2jWQa1w', 'ueOUSjdAZY8', '90iK6gGvG_g', 'hsaPfEvForM', 'jb8XlF2dkoY', 'WhkNQ3g0U64', '_suB8xV9aPc', 'dWHSt0BVlv0', 'xJVWL7eMir0', 'h48xzQR3wNQ', 'S5gX-LLAZIM', 'LNlzx-YX8rI', 'WzkBZ0byoYE', 'weCZ1WynbMI', '3dOxGYkpVbE', '9dLXZrw6nac', 'i3xK7Nc414Q', 'H7YMumanHBA', '4p-G7fGhqRk', 'yLR1w4tZ36I', '-DiOp9vAEuM', 'O1o9m9T1c3k', '7hZYh9qXxe4', 'aE623ff7zkM', 'eXJGjbDo5KY', 'O52sweYbCyI', 'cLSxasHg9WY', 'l6XhSFAyvO0', 'nJIEIzF7tDw', 'RehbnzKHS28', '0OQJDd3QqQM', 'V6KPbGLYL4A', 'OIqm909GYYo', 'xN2PRAd8IZQ', 'AK7_m-aThfw', 'CYszyA2Xzdg', 'wT9ICgxRPYY', 'XruOBp7yPXU', 'SwSbnmqk3zY', '8p_OzqIJ_p4', '0Hhqf8L-b_0', 'M2NzvnfS-hI', 'QNfnuK-1YYY', 'PuBadaR8qC4', 'FNYdBLwZ6cE', 'zAmJPdZu8Rg', 'HJAwAKwFX-A', 'kY5HtrkjSj0', 'LCVSmkyB4v8', '6x7vHXfRAP0', '-DrSbc8B0WI', 'gsa1oFn9n0M', 'Ww71knvhQ-s', 'Jsnw6HLASZA', 'V_BozMwoYe4', '0wjPsKDrYt8', '1-z9ptlBar4', '35dXEQJkFE8', 'jgNB4GN1UaQ', 'fhxByMe0mq8', '5bwpXLHzZRo', 'UzOnFDmoJ9w', 'HNChkuE6HyA', '2gFqUWO-AWM', 'NvdSKgQcyuc', 'BBb_duZIusU', 'PRGkYivK2xI', 'M323OL6K5vs', 'i7BjHjRafU8', 'r2asdRpr3uw', 'Hl4NZB1XR9c', '1aybOgni7lI', 'j09EQ-xlh88', '7nzTDrio7vY', 'J-uCLHTIWZ4', '_BMPh5M4BIY'], 'video_details': [{'video_id': '0QcEqFrhb_Y', 'channelTitle': 'techTFQ', 'title': 'Learn SQL from me | Live SQL Training | SQL Bootcamp', 'description': 'In this video, I highlight the 3 reasons why many are struggling to learn SQL and how I can help with a couple of the reasons. I talk about the upcoming SQL Bootcamp on Lighthall and who should join this SQL Bootcamp.\nAnyone with zero knowledge of SQL or any programming language can join my SQL BootCamp and learn SQL.\n\nAll details about the SQL BootCamp are mentioned here: \nhttps://techtfq.com/sql-bootcamp\n\nJoin the SQL Bootcamp here:\nhttps://www.lighthall.co/class/242f82c8-8220-40e8-9674-ed6b3f596f09\n\n\nHere is a quick summary of the SQL Bootcamp below:\n\n -- Weekend class - 20 live sessions - reduced price ($30 / INR 2400)\n -- Beginner to Advance level SQL - Suitable for beginners\n -- Starts: 03-Jun-2023\n -- Timing: 07:30 pm IST (Indian time) / 10:00 am EST (Eastern time) / 04:00 pm CET (Central European time)\n -- Days: Only on Weekends (Saturday & Sunday)\n -- If you miss a live class, then watch the recordings.\n -- Recording will be available for up to 1 year\n\nTimeline of the video:\n00:00 Intro\n00:46 Reason no 1) for struggling to learn SQL\n02:01 Reason no 2) for struggling to learn SQL\n02:41 Reason no 3) for struggling to learn SQL\n03:17 How can I help in solving these problems?\n04:54 Details about my upcoming SQL Bootcamp\n05:13 Quick summary of my upcoming SQL Bootcamp\n\nThank you!', 'tags': ['sql', 'learn sql for beginners', 'learn sql', 'sql course', 'sql training', 'live sql training', 'sql bootcamp', 'sql tutorial', 'techtfq', 'sql techtfq', 'techtfq sql', 'sql practice', 'sql queries'], 'publishedAt': '2023-05-25T14:35:13Z', 'viewCount': '19761', 'likeCount': '565', 'favouriteCount': None, 'commentCount': '162', 'duration': 'PT9M51S', 'definition': 'hd', 'caption': 'false'}, {'video_id': 'smztq8sRAhk', 'channelTitle': 'techTFQ', 'title': 'Learn Python here | Learn Python Programming here', 'description': 'In this video, I will showcase a dedicated online platform for learning Python.  This platform contains multiple different Python courses which are dedicated to complete beginners and also for advanced learners. You will find Python courses specific to Data science and data processing too. \n\nLink to the platform: https://fas.st/t/z1UT6m6w\nPROMO CODE: adtfq10\nThe above promo code gives a 10% discount but will be active only until 01/08/2023\n\nJoin my Live Training SQL Bootcamp starting 03-Jun-2023\nMore details: https://techtfq.com/sql-bootcamp\nJoin Bootcamp: https://www.lighthall.co/class/242f82c8-8220-40e8-9674-ed6b3f596f09\n\nThanks,\nThoufiq', 'tags': ['learn python', 'python for beginners', 'python course', 'python online course', 'techtfq python', 'techtfq', 'techtfq sql', 'learnpython.com', 'python tutorial', 'python tutorial for beginners', 'best python course', 'best platform to learn python'], 'publishedAt': '2023-05-16T13:45:59Z', 'viewCount': '13060', 'likeCount': '241', 'favouriteCount': None, 'commentCount': '20', 'duration': 'PT6M30S', 'definition': 'hd', 'caption': 'false'}, {'video_id': '7skZzocEU6c', 'channelTitle': 'techTFQ', 'title': 'Solving a Complex SQL Interview problem | Practice SQL Queries', 'description': 'In this video, let us solve a complex SQL interview problem. This is a REAL SQL Interview question that might seem impossible to solve just by using SQL at first. But during the video, I will simplify the problem by breaking it into multiple parts. \nWe shall first determine an approach that can solve such problems easily and then write the SQL query to solve this problem.\n\nYou can download the dataset, scripts, and solution from my website below:\nhttps://techtfq.com/blog/lets-simplify-and-solve-a-complex-sql-interview-problem\n\n\n🔴 My Recommended courses 👇\n✅ Learn complete SQL: https://learnsql.com/?ref=thoufiqmohammed\n\n✅ Practice SQL Queries: https://www.stratascratch.com/?via=techTFQ\n\n✅ Learn Python: https://codebasics.io/courses/python-for-beginner-and-intermediate-learners?refId=70170e4c-7511-4c83-b769-c5cc8339c731\n\n✅ Learn Power BI: https://codebasics.io/courses/power-bi-data-analysis-with-end-to-end-project?refId=4b1e1886-3252-4bf1-86f4-7d603dab692f\n\n\n🔴 WATCH MORE VIDEOS HERE 👇\n\n✅ SQL Tutorial - Basic concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HQQ_COgGb7kf_1H8UWUBxO\n\n✅ SQL Tutorial - Intermediate concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FD9XspliRM_HZM_jK7tkii\n\n✅ SQL Tutorial - Advance concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GbmgiW4TWVnxhjMFOIf0Q7\n\n✅ Practice Solving Basic SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9F66P3GFo5O6nJ4DfZNhVsp\n\n✅ Practice Solving Intermediate SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EIYmNXJ8ZtQ1bmLIpt0SpV\n\n✅ Practice Solving Complex SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9Fahr7taauUx5RnTfuGyL--\n\n✅ Data Analytics Career guidance:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FDsr995DjwCy9XNaIukb8P\n\n✅ SQL Course, SQL Training Platform Recommendations:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GqF1Q_zn8KnYvFgtEOh-2n\n\n✅ Python Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FePZXIo4jpsupqp3X0w2SW\n\n✅ Git and GitHub Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EI1MPlqqDpe3bgr8RJZE0b\n\n✅ Data Analytics Projects:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HwT_uStsDdJbuBOt_XD0ch\n\nTHANK YOU,\nThoufiq', 'tags': ['sql', 'learn sql', 'sql query', 'sql queries', 'sql problem', 'sql interview', 'sql interview query', 'sql interview problem', 'solving sql query', 'practice sql query', 'complex sql query', 'sql techtfq', 'techtfq sql', 'techtfq', 'sql interview questions'], 'publishedAt': '2023-03-21T13:00:12Z', 'viewCount': '31550', 'likeCount': '899', 'favouriteCount': None, 'commentCount': '99', 'duration': 'PT32M9S', 'definition': 'hd', 'caption': 'false'}, {'video_id': 'LZGaRcDxj8I', 'channelTitle': 'techTFQ', 'title': 'REAL SQL Interview Problem | Hierarchical data in SQL', 'description': 'In this video let us solve a real SQL interview problem. This problem is to find the hierarchy of employees. \n\nWe shall first understand the problem statement and the given data before solving the problem.\nDuring the video, we shall also see how to debug a recursive SQL query. We shall try to come up with the different queries SQL generates during each iteration of the recursive SQL query. This will hopefully give you a complete understanding of how recursive SQL query works.\n\n🔴 My Recommended courses 👇\n✅ Learn complete SQL: https://learnsql.com/?ref=thoufiqmohammed\n\n✅ Practice SQL Queries: https://www.stratascratch.com/?via=techTFQ\n\n✅ Learn Python: https://codebasics.io/courses/python-for-beginner-and-intermediate-learners?refId=70170e4c-7511-4c83-b769-c5cc8339c731\n\n✅ Learn Power BI: https://codebasics.io/courses/power-bi-data-analysis-with-end-to-end-project?refId=4b1e1886-3252-4bf1-86f4-7d603dab692f\n\n\n🔴 WATCH MORE VIDEOS HERE 👇\n\n✅ SQL Tutorial - Basic concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HQQ_COgGb7kf_1H8UWUBxO\n\n✅ SQL Tutorial - Intermediate concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FD9XspliRM_HZM_jK7tkii\n\n✅ SQL Tutorial - Advance concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GbmgiW4TWVnxhjMFOIf0Q7\n\n✅ Practice Solving Basic SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9F66P3GFo5O6nJ4DfZNhVsp\n\n✅ Practice Solving Intermediate SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EIYmNXJ8ZtQ1bmLIpt0SpV\n\n✅ Practice Solving Complex SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9Fahr7taauUx5RnTfuGyL--\n\n✅ Data Analytics Career guidance:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FDsr995DjwCy9XNaIukb8P\n\n✅ SQL Course, SQL Training Platform Recommendations:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GqF1Q_zn8KnYvFgtEOh-2n\n\n✅ Python Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FePZXIo4jpsupqp3X0w2SW\n\n✅ Git and GitHub Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EI1MPlqqDpe3bgr8RJZE0b\n\n✅ Data Analytics Projects:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HwT_uStsDdJbuBOt_XD0ch\n\nTHANK YOU,\nThoufiq', 'tags': ['sql', 'learn sql', 'sql queries', 'sql query', 'solving sql query', 'solving sql problem', 'sql interview query', 'sql interview problem', 'real sql interview', 'real sql interview problem', 'recursive sql', 'hierarchical data in sql', 'sql hierarchy', 'sql recursion', 'sql tutorial', 'sql techtfq', 'techtfq sql', 'techtfq', 'sql interview questions and answers', 'sql interview questions', 'interview question', 'sql interview'], 'publishedAt': '2023-03-14T13:00:09Z', 'viewCount': '17114', 'likeCount': '676', 'favouriteCount': None, 'commentCount': '56', 'duration': 'PT22M9S', 'definition': 'hd', 'caption': 'false'}, {'video_id': 'rBPQ5fg_kiY', 'channelTitle': 'techTFQ', 'title': 'Complete guide to Database Normalization in SQL', 'description': 'This is a complete guide for anyone to understand Database Normalization in SQL. I will not just explain the Normalization concepts but also show you step by step process of normalizing a de-normalized dataset taken from Kaggle by following the different levels of normalization (Normal forms).\n\nThe video is divided into 3 sections: \nIn the first section, I will explain the basic concepts of normalization and the different levels of normalization (different normal forms), and some key points you need to know to better understand normalization.\nIn the second section, I will explain all the above concepts in detail with proper examples. We shall use a de-normalized dataset taken from Kaggle for illustration purposes. We shall follow different normal forms to normalize the Kaggle dataset which should give a complete understanding of how to normalize any dataset.\nFinally, in the third and last section, I shall explain the different anomalies that exist in a de-normalized dataset such as insertion, updation, and deletion anomalies. We shall also see how a normalized database can overcome these anomalies.\n\nTimestamp:\n00:00 Intro\n00:46 1. What is Normalization\n03:12 Different levels of Normalization\n05:14 2. Step-by-Step Normalizing a dataset\n07:35 First Normal Form (1NF)\n12:44 Second Normal Form (2NF)\n25:59 Third Normal Form (3NF)\n32:42 3. Different Anomalies (Insertion, Updation, Deletion Anomalies)\n37:10 Deletion Anomalies\n39:08 Updation Anomalies\n\n\n🔴 My Recommended courses 👇\n✅ Learn complete SQL: https://learnsql.com/?ref=thoufiqmohammed\n\n✅ Practice SQL Queries: https://www.stratascratch.com/?via=techTFQ\n\n✅ Learn Python: https://codebasics.io/courses/python-for-beginner-and-intermediate-learners?refId=70170e4c-7511-4c83-b769-c5cc8339c731\n\n✅ Learn Power BI: https://codebasics.io/courses/power-bi-data-analysis-with-end-to-end-project?refId=4b1e1886-3252-4bf1-86f4-7d603dab692f\n\n\n🔴 WATCH MORE VIDEOS HERE 👇\n\n✅ SQL Tutorial - Basic concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HQQ_COgGb7kf_1H8UWUBxO\n\n✅ SQL Tutorial - Intermediate concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FD9XspliRM_HZM_jK7tkii\n\n✅ SQL Tutorial - Advance concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GbmgiW4TWVnxhjMFOIf0Q7\n\n✅ Practice Solving Basic SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9F66P3GFo5O6nJ4DfZNhVsp\n\n✅ Practice Solving Intermediate SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EIYmNXJ8ZtQ1bmLIpt0SpV\n\n✅ Practice Solving Complex SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9Fahr7taauUx5RnTfuGyL--\n\n✅ Data Analytics Career guidance:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FDsr995DjwCy9XNaIukb8P\n\n✅ SQL Course, SQL Training Platform Recommendations:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GqF1Q_zn8KnYvFgtEOh-2n\n\n✅ Python Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FePZXIo4jpsupqp3X0w2SW\n\n✅ Git and GitHub Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EI1MPlqqDpe3bgr8RJZE0b\n\n✅ Data Analytics Projects:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HwT_uStsDdJbuBOt_XD0ch\n\nTHANK YOU,\nThoufiq', 'tags': ['database normalization', 'database normalization 1nf 2nf 3nf', 'sql normalization', 'database normalization in sql', 'normalize database', 'normal forms', '1nf', '2nf', '3nf', 'sql', 'learn sql', 'sql turorial', 'normalization in sql', 'normalization tutorial', 'normalization in database', 'sql techtfq', 'techtfq', 'techtfq sql', 'insertion anomalies', 'deletion anomalies', 'updation anomalies', 'anomalies in dbms', 'dbms normalization', 'data redundancy', 'candidate key', 'partial dependancy', 'transitive dependancy'], 'publishedAt': '2023-03-07T13:00:07Z', 'viewCount': '45504', 'likeCount': '2142', 'favouriteCount': None, 'commentCount': '221', 'duration': 'PT40M51S', 'definition': 'hd', 'caption': 'false'}, {'video_id': 'hvwltYazuQo', 'channelTitle': 'techTFQ', 'title': 'SQL Live class on Lighthall | Learn SQL from Basic to Advance in SQL Bootcamp', 'description': "In this video, I talk about the Live SQL Classes that I'll be taking on Lighthall from 01-Feb-2023. This SQL Bootcamp will cover Basic, Intermediate and Advance SQL.\n\nTimestamp:\n00:00 Intro\n00:40 Bootcamp details and Format\n02:16 Advantages of live class training over recorded courses\n04:22 Difference between learning SQL from my YouTube videos and SQL Bootcamp\n05:20 Who is this SQL bootcamp for?\n\n - 20 Live & Interactive SQL classes of 1.5 hrs each.\n - 3 classes per week\n - Starts on 01-Feb-2023\n - Recording will be available for 1 year\n - Certification provided\n - Cost = USD $50\n - Timing: 09:30 pm IST / 11:00 am EST\n\nJOIN Bootcamp here: https://www.lighthall.co/class/b608abfc-e3f4-43b3-a008-14bf8403b821\n\nOR go to my website for more details:\nhttps://techtfq.com/sql-bootcamp\n\nThanks,\nThoufiq", 'tags': ['sql', 'sql queries', 'learn sql', 'sql live class', 'sql live classes', 'sql bootcamp', 'sql course', 'sql training', 'sql basic', 'sql advance', 'sql tutorial', 'sql for beginners', 'sql techtfq', 'techtfq sql', 'techtfq', 'how to learn sql'], 'publishedAt': '2023-01-26T07:00:07Z', 'viewCount': '11763', 'likeCount': '247', 'favouriteCount': None, 'commentCount': '150', 'duration': 'PT6M46S', 'definition': 'hd', 'caption': 'false'}, {'video_id': 'a-hFbr-4VQQ', 'channelTitle': 'techTFQ', 'title': 'How to learn SQL for free | Roadmap to learning SQL', 'description': 'In this video, you will find complete roadmap on how to learn SQL for Beginners, Intermediate level, Advanced level and for database developers.\nYou will know how to choose a database and what SQL concepts you need to learn to have basic, intermediate, advanced and developer level knowledge of SQL.\n\nCheckout Bootcamp courses on Springboard: https://www.springboard.com/\n\nUse below promo code to get discounts on any Springboard course:\nPromo code: TechTFQNEWYEAR offers $1,250 (valid until 05-Jan-2023)\nPromo code: TechTFQ offers $1,000\n\nTimestamp:\n00:00 Intro of SQL Learning Roadmap\n01:44 Pre-Requisites required before learning SQL (which database, IDE etc)\n06:10 Springboard bootcamp course\n08:30 Basic SQL\n15:42 Intermediate level of SQL\n21:35 Advanced SQL\n24:08 SQL required for DB developers or SQL developers\n\nLearning Resources & Practice Platforms mentioned in the video can be found in detail in my blog. Link below:\nhttps://techtfq.com/blog/how-to-learn-sql-for-free-roadmap-to-learning-sql\n\n\n🔴 My Recommended courses 👇\n✅ Learn complete SQL: https://learnsql.com/?ref=thoufiqmohammed\n\n✅ Practice SQL Queries: https://www.stratascratch.com/?via=techTFQ\n\n✅ Learn Python: https://codebasics.io/courses/python-for-beginner-and-intermediate-learners?refId=70170e4c-7511-4c83-b769-c5cc8339c731\n\n✅ Learn Power BI: https://codebasics.io/courses/power-bi-data-analysis-with-end-to-end-project?refId=4b1e1886-3252-4bf1-86f4-7d603dab692f\n\n\n🔴 WATCH MORE VIDEOS HERE 👇\n\n✅ SQL Tutorial - Basic concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HQQ_COgGb7kf_1H8UWUBxO\n\n✅ SQL Tutorial - Intermediate concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FD9XspliRM_HZM_jK7tkii\n\n✅ SQL Tutorial - Advance concepts:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GbmgiW4TWVnxhjMFOIf0Q7\n\n✅ Practice Solving Basic SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9F66P3GFo5O6nJ4DfZNhVsp\n\n✅ Practice Solving Intermediate SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EIYmNXJ8ZtQ1bmLIpt0SpV\n\n✅ Practice Solving Complex SQL Queries:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9Fahr7taauUx5RnTfuGyL--\n\n✅ Data Analytics Career guidance:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FDsr995DjwCy9XNaIukb8P\n\n✅ SQL Course, SQL Training Platform Recommendations:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9GqF1Q_zn8KnYvFgtEOh-2n\n\n✅ Python Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9FePZXIo4jpsupqp3X0w2SW\n\n✅ Git and GitHub Tutorial:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9EI1MPlqqDpe3bgr8RJZE0b\n\n✅ Data Analytics Projects:\nhttps://www.youtube.com/playlist?list=PLavw5C92dz9HwT_uStsDdJbuBOt_XD0ch\n\nFTC disclaimer: This video was sponsored by Springboard.\n\nTHANK YOU,\nThoufiq', 'tags': ['learn sql', 'how to learn sql', 'how to learn sql for free', 'sql tutorial', 'sql learning resources', 'sql practice platforms', 'sql roadmap', 'roadmap to learning sql', 'roadmap sql', 'sql for beginners', 'sql for intermediate', 'advance sql', 'sql for db developers', 'prerequisites for learning sql', 'sql learning prerequisites', 'which database for learning sql'], 'publishedAt': '2022-12-28T13:00:10Z', 'viewCount': '354674', 'likeCount': '11305', 'favouriteCount': None, 'commentCount': '364', 'duration': 'PT27M20S', 'definition': 'hd', 'caption': 'false'}, {'video_id': 'pMNcPLc9Z7c', 'channelTitle': 'techTFQ', 'title': 'Solving an SQL Interview Problem', 'description': "In this video, let's solve an SQL interview query taken from LeetCode.\nThe problem might seem complex at first but there is a very simple solution to solve such problems so lets explore it in this video.\n\nLink to complete video: https://youtu.be/zZKb8FQRShs", 'tags': ['sql', 'learn sql', 'sql tutorial', 'solving sql queries', 'sql in

In [212]:
def find_none_values(data):
    null_keys = []
    for key, value in dict.items():
        if value is None:
            null_keys.append(key)
    return null_keys

# Example dictionary
data = {'channel_details' : channel_details,
            'video_ids' : video_ids,
            'video_details' : video_df,
            'comment_details' : comment_df
               }

null_keys = find_none_values(data)
print("Keys with None values:", null_keys)

TypeError: unbound method dict.items() needs an argument

In [197]:
output= main(youtube,channel_id)

TypeError: main() takes 1 positional argument but 2 were given

# mongodb connection

In [205]:
import pymongo

In [206]:
client = pymongo.MongoClient("mongodb://localhost:27017")

In [207]:
mydb =client["newone"]

In [208]:
information = mydb.data

In [209]:
information.insert_many(data)

TypeError: documents must be a non-empty list